### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#1]

**Comment by DennisSnijder** [comment]
I know this is something ALOT of bunq users want 😛 
https://together.bunq.com/topic/dark-night-mode

**Comment by basst85** [comment]
Maybe you can base it on the Twitter "night mode" colors? So very dark blue and not all black ?

**Comment by DennisSnijder** [comment]
@basst85 we are using Material UI, they already provide a dark theme.
Check it out 😄 
http://www.material-ui.com/#/customization/themes

**Comment by Crecket** [comment]
Yeah I definitely prefer blue-ish themes over just black. Material-ui supports a dark theme by default which we can test 
https://material-ui-1dab0.firebaseapp.com/customization/themes/#dark-light-theme

**Comment by Crecket** [comment]
We are using the alpha version of material-ui so checkout  https://material-ui-1dab0.firebaseapp.com/customization/themes/#dark-light-theme
@DennisSnijder

**Comment by Crecket** [comment]
Working on it! 
![bca4d82594ac70c12e7ba965fa426600](https://user-images.githubusercontent.com/7481136/31671728-f13a5fa0-b35a-11e7-8114-2a3916011857.png)

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/31680215-f634ec14-b373-11e7-88b4-5615dde328f2.png)
Added a options menu and you can now change the theme
