### ISSUE TITLE
Starting the app without an internet connection causes issues

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#100]
If you open bunqdesktop without an internet connection 0 accounts are shown and hitting refresh causes the following.

![image](https://user-images.githubusercontent.com/7481136/34084037-30d06106-e37a-11e7-90eb-531a51b87518.png)

**Comment by DennisSnijder** [comment]
Perhpas we can do something cool like offline usage? 😄

**Comment by Crecket** [comment]
I plan on adding full offline support once we setup proper caching for all the different endpoints and requests

**Comment by Crecket** [comment]
Seems to be fixed now but we'll continue to improve the offline experience in future versions
