### ISSUE TITLE
Display joint accounts when the API adds the required functionality

### ISSUE THREAD

**Issue by gldrenthe89** [BunqCommunity/BunqDesktop#104]
The app isn't showing al of my IBAN that are co owned by me en my wife (en/of)

**Comment by DaniWinter** [comment]
The Bunq API doesn't support joint accounts (yet). I doubt it will support it in the future because of the legal limitations of a joint account.

**Comment by Crecket** [comment]
Like @DaniWinter said the joint accounts aren't supported yet but it is one of the features we'll add as soon as possible when support is added. 

I'll add this issue to the backlog for others to find 👍

**Comment by Crecket** [comment]
We can sort of track progress on the feature here bunq/sdk_php#76

**Comment by OGKevin** [comment]
@Crecket Just a little heads up. There seems to be reports that joint accounts are being returned 😊 However it seems that there is a bug not sure yet if this is in the API or SDK. If its the later then it wont affect you ofc.

**Comment by Crecket** [comment]
Alright, thanks for letting me know 👍  @OGKevin
