### ISSUE TITLE
The API key or IP you are currently on is not valid for the PRODUCTION bunq environment.

### ISSUE THREAD

**Issue by IngeN86** [BunqCommunity/BunqDesktop#105]
I accidentally clicked remove password. Then i entered a new one and suddely the api key is not working anymore and gives this error.
So do i have to get a new api key now again? Or why does it suddenly not work anymore

**Comment by Crecket** [comment]
Are you using a wildcard api key? Usually this error is caused when you are trying to log-in on a different IP address or when you use a Developer key on the Production environment or the other way around.

**Comment by IngeN86** [comment]
I dont know, just the api key i got from the app. And i use the same bunqdesktop as before? And also from same laptop, internet connection etc..

**Comment by IngeN86** [comment]
Sorry, just tried again, did same thing and now it works? So thats weird;)
