### ISSUE TITLE
We received the following error while loading your master card payments: User credentials are incorrect. Incorrect API key or IP address.

### ISSUE THREAD

**Issue by IngeN86** [BunqCommunity/BunqDesktop#106]
So now i get this... i dont understand? Same laptop, same password.

**Comment by IngeN86** [comment]
Removed my password and thought see if that helps, now i get same as before
The API key or IP you are currently on is not valid for the PRODUCTION bunq environment.

at the moment this is the only banking i can do, since my phone broke, so not happy this is not working correct every time.

**Comment by Crecket** [comment]
We're still in early development so you shouldn't be relying on this application in any way. 

There are a couple of issues with storing the API key right now which we are working on but I don't know when it'll be fixed.

You can try installing an older version like 0.7.1 or 0.7.3 to see if that helps

**Comment by IngeN86** [comment]
I hope it will be fixed by monday.. I have to rely on it since i dont have a phone at the moment.

**Comment by Crecket** [comment]
Likely related to #96 so I'll close it for now
