### ISSUE TITLE
cursor jumps to end of amount when pressing "." or "0x" in the amount field

### ISSUE THREAD

**Issue by petervdv** [BunqCommunity/BunqDesktop#110]
On the Pay or Request tab if you put in an amount, the cursor moves to the next spot. But if you directly press "." the cursor moves to the end instead of directly after the dot. Also when you press a zero first, for example if you input "05", the cursor moves to the end instead of after the "5".

Using Ubuntu and BunqDesktop 0.7.4

**Comment by Crecket** [comment]
I managed to fix a few minor issues with the input but I can't find decent alternatives for the number input that is both decent looking and supports the features we need. Creating a custom one is a lot of work so for now I'm going to mark this as fixed
