### ISSUE TITLE
Error loading dashboard: Insufficient authorisation

### ISSUE THREAD

**Issue by nimpie** [BunqCommunity/BunqDesktop#113]
When using BunqDesktop 0.7.4 I receive an error loading the Dashboard:

"Something went wrong
We received the following error while loading your master card payments: Insufficient authorisation"

It did not happen before. It just came up today.

**Comment by Crecket** [comment]
Could you try logging in and out of the client to force it to create a new session?

**Comment by nimpie** [comment]
That did the trick. It is loading again without errors.

**Comment by Crecket** [comment]
Alright thanks! Looks like the client isn't properly invalidating the old session, I'll try to fix this behavior in the next release
