### ISSUE TITLE
Transaction details arrow always points to the right

### ISSUE THREAD

**Issue by cascer1** [BunqCommunity/BunqDesktop#119]
It seems like the arrow between both parties involved in a transaction always points right.

![image](https://user-images.githubusercontent.com/7243299/36860673-41243018-1d82-11e8-9d20-1ef800e6b086.png)

However, sometimes this incorrectly displays the actual situation. For example, I paid for tickets to a convention using my MasterCard that is linked to my primary account. 

![image](https://user-images.githubusercontent.com/7243299/36860737-6dc19688-1d82-11e8-898d-8025a9c91436.png)

This suggests that the amount was transferred from the merchant to me.

**Details**:

* Version 0.8.0
* Windows 10 (1709)

**Steps to reproduce**:

1. Login to the desktop client
2. Click on any transaction to view its details
3. Observe the arrow between the images of both parties

**Expected behaviour**:

The arrow should indicate the direction of the money flow in a transaction, instead of always pointing right.

**Comment by Crecket** [comment]
Thanks for the report! I fixed it and it'll be available in the next release
