### ISSUE TITLE
Card CVC generation functionality

### ISSUE THREAD

**Issue by Crecket** [bunqCommunity/bunqDesktop#131]
While working on #59 it became clear this is a lot more difficult than expected. The docs do not say how exactly this request must be encrypted which requires more work to reverse engineer this behavior from the bunq sdks in other languages.

**Comment by OGKevin** [comment]
Call encryptions are done via the server public key. bunq will decrypt these with the server private key exchanged during the `installation` call. You must also set some headers. 

I think these are good examples:

https://github.com/bunq/sdk_php/blob/652e650aa35a8c0c598653e986ac7f68d4808bdd/src/Http/ApiClient.php#L269-L272

https://github.com/bunq/sdk_php/blob/652e650aa35a8c0c598653e986ac7f68d4808bdd/src/Http/Handler/RequestHandlerEncryption.php#L45-L66

**Comment by Crecket** [comment]
This is now possible 🎉
