### ISSUE TITLE
Statistics page refresh doesn't load all data immediately

### ISSUE THREAD

**Issue by cascer1** [BunqCommunity/BunqDesktop#145]
Hey

I'm using version 0.8.1 of the app, and noticed that the stats page didn't immediately show all stats for the selected account. Every time I pressed the refresh button, it added about a week of data to the display.

[See this video](https://i.eliens.co/1522061500149.mp4)

Is this something I'm doing wrong, or is this a bug?

**Comment by Crecket** [comment]
It is supposed to do 50 items a time which are then all stored so you only have to do this once. But I've noticed that it only does like ~10 each time for some reason so I'll look into that to speed up the initial sync

I do plan on adding automatic updates in the future where it'll just automatically start updating all the items when you open the application
