### ISSUE TITLE
Package manager for Windows

### ISSUE THREAD

**Issue by IcyPalm** [BunqCommunity/BunqDesktop#146]
With the recent activity including brew cask(Mac)🍏  and SnapCraft(Ubuntu)💻  I wondered if Windows(10) users could see some love ❤️ 

For Windows 10 user it would be very nice to be able to install bunqDesktop with https://chocolatey.org/

Or maybe even the Microsoft Store?

**Comment by Crecket** [comment]
Currently under review: https://chocolatey.org/packages/bunqdesktop

**Comment by Crecket** [comment]
Accepted after review:
"Will keep an eye out for the next package version, and assuming everything goes well, we can get this moved over to be a trusted package."
