### ISSUE TITLE
Amounts not so good readable with dark theme

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#16]
The payment amounts are not so good readable with the new dark theme.
Maybe use a other color and bigger font?

Extra info:
I'm using Windows 10 as OS.

![amount_dark](https://user-images.githubusercontent.com/6396615/31707496-caeab6b4-b3ec-11e7-852c-db8b464964bc.png)

**Comment by DennisSnijder** [comment]
This has been fixed, colors are a bit brighter. This makes it way more readable 😄
![image](https://user-images.githubusercontent.com/6953846/31725401-93d13a6c-b424-11e7-8b9b-d603cd569a74.png)

**Comment by DennisSnijder** [comment]
Will be available in the next release.
