### ISSUE TITLE
Display clearer error messages for the user

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#17]
Certain functionality fails silently without letting the user know something went wrong. Using the MainSnackbar or MainDialog we should notify the user that something went wrong

**Comment by Crecket** [comment]
I added a few notifications in aa9d034 which I'll clean-up and some more later once we have proper options to disable an error message.

**Comment by basst85** [comment]
This is also nice, to log the full (technical) API endpoint errors: https://www.npmjs.com/package/electron-log
You can also write some request info.
