### ISSUE TITLE
Account balance calculation after filtering

### ISSUE THREAD

**Issue by Cheaternl** [BunqCommunity/BunqDesktop#170]
I have 20 accounts, but on several accounts, I do put money that is meant for separate purposes. 
Think of it like creating budgets within one account, whereas Bunq say that each budget should deserve an own account.  As I said, I already have 20 accounts, so I DO budget on each account.

For instance, I have one account with my savings. Let's say I have a saving called 'Presents Family', which is meant for .. yes... you are right, buying presents for my family.  However the account has also other savings. 
Which makes it cloudy for me, how much money I have saved for this 'Presents Family'.

Now, this was my little introduction. I now bow for you, the creator of BunqDesktop, because you've finally implemented categories and a rule system! This is EXACTLY what I needed to apply on my casus/description above. I now attach a category named 'Presents Family' to the money transfers that have a particular description (description is always the same) via the rule system. Than I can filter on this category easily. SUPERB!

However, I still have to calculate the savings myself, after filtering on that category. See screenshot:
![virtual-balance](https://user-images.githubusercontent.com/8473337/38573312-fb63f0fc-3cf5-11e8-8a8f-4f1e51096937.jpg)
I called it 'Virtual balance', because it's not my real balance. 

My request:
Can you add a 'balance' which displays the sum of money transfers, and is calculated on what I have filtered on? From the screenshot, I only need to see: "€ -45.40".

**Comment by Crecket** [comment]
Definitely something we could do. I'm already working on showing that balance on the stats page with outgoing, incoming and total balance for each category per timescale 👍

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/38638542-e4bbe416-3dce-11e8-9dd7-bd2666f2112f.png)
Will need some testing with the different mastercard types and statuses and other minor UI changes

**Comment by Cheaternl** [comment]
Nice nice! And do I need to choose to view ALL transactions before I get the 'Total change', or can I just view 10, and in the background, 'Total change' calculates this based on ALL transactions in that account?

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/38665459-bb8bbdd2-3e3c-11e8-8b14-58d948023158.png)
Clicking the info icon at the top is always possible. And no because payments per monetary account are visible now it only calculates data for that one account

**Comment by Cheaternl** [comment]
With this I can work! Thank you very much!
