### ISSUE TITLE
Display payment type

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#18]
The payment/transaction type is missing in the payment info screen.
Like: iDEAL, pintransaction, cash withdrawal..

**Comment by basst85** [comment]
The information on https://doc.bunq.com/api/1/call/payment/method/get is not 100% up-to-date.
You have parment type "MASTERCARD", this is for pintransactions and also cash withdrawals, so that makes it a bit tricky.

And the there is also a undocumented response attribute Payment->counterparty_alias->merchant_category_code, with one of these values: https://github.com/greggles/mcc-codes/blob/master/mcc_codes.csv

**Comment by craftbyte** [comment]
@basst85 the MASTERCARD type shouldn't be a problem, since the subtypes still apply

**Comment by basst85** [comment]
@craftbyte In the API documentation (https://doc.bunq.com/api/1/call/payment/method/get) there is a sub_type, but i don't see any in the real payment response JSON (in production)..

**Comment by Crecket** [comment]
It now shows the `type` that is included with the payment object. I'll look into adding the sub types and/or merchant categories later

**Comment by basst85** [comment]
https://together.bunq.com/topic/sub_type-missing-in-payment-response#comment-20397
