### ISSUE TITLE
WISH: Draft payments with insufficient funds.

### ISSUE THREAD

**Issue by timstapersma** [BunqCommunity/BunqDesktop#188]
It would be awesome if I am able to draft payments while I do not have sufficient funds.
This feature will make the your awesome app even more awesome!

Tim

**Comment by Crecket** [comment]
Done 👍 will be added to the next release

**Comment by timstapersma** [comment]
Wow, that is just awesome. You are the best😃

Op di 24 apr. 2018 21:47 schreef Gregory Goijaerts <notifications@github.com
