### ISSUE TITLE
Virus Alert in Version 0.8.4

### ISSUE THREAD

**Issue by unimol** [BunqCommunity/BunqDesktop#189]
Avast Anti-Virus-Scanner put the installer into the virus container.
**The installer is classified as a potentially threat.**

This happend on all my devices with Avast.
Latest Avast version and antivirus database.

**Comment by basst85** [comment]
I think it's a false positive, check this online scanresults: https://www.virustotal.com/nl/file/43f78c307cdbf236606ca3d098340e3280257042014fd8c024fa6b5e6ba5a313/analysis/1524655725/

**Comment by Crecket** [comment]
I can pretty much guarantee that the files listed in the last few releases are all virus free. If you are worried about which files you downloaded there are checksums available at the bottom of every release ([Version 0.8.4](https://travis-ci.org/BunqCommunity/BunqDesktop/jobs/365639296)) which you can validate or build the application yourself by using the commands listed in the readme
