### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by DennisSnijder** [bunqCommunity/bunqDesktop#19]
In the near future we want to support notifications for the BunqDesktop client.

This issue is to discuss on how we should approach this since the API only allows callbacks at the moment.

**Comment by ntimo** [comment]
Maybe you could create a helper application that calls the api for updates and if there is sone shows the user a notification. The helper could be started at system boot without having to start the BunqDesktop app itself.

**Comment by DennisSnijder** [comment]
@ntimo this could be one solution indeed.
Maybe we could do something like setting up a simple server which catches the notifications and transmits the events to the correct client via sockets. (Would be really easy with https://pusher.com)

**Comment by ntimo** [comment]
@DennisSnijder First I think the notification checking should be done local on the device because of the privacy. And also using a service like this would cost you money/the user. And that is not a perfekt solution in my eyes.

**Comment by DennisSnijder** [comment]
@Crecket suggestions on this topic? 😝

**Comment by Crecket** [comment]
The most reasonable and secure solution would be to pull every 10-30 seconds (Perhaps make this configurable/opt-in?)

**Comment by ntimo** [comment]
@Crecket yes, that would be great +1

**Comment by Crecket** [comment]
I want to add that we already have a component I used to display default Chrome notifications found in `src/react/Helpers/Notification.js`. This should be able to show notifications even when the app is in the background

**Comment by basst85** [comment]
You can also create a system tray icon functionality to keep the app alive.

**Comment by DennisSnijder** [comment]
Small update on this topic.
We requested an "/events" endpoint to the Bunq dev team.
(Lets hope they will implement it 😄 )
