### ISSUE TITLE
How to export category rules

### ISSUE THREAD

**Issue by Cheaternl** [BunqCommunity/BunqDesktop#191]
Hi, 
I don't see any Export button in the category rules page. However, there is an Import button.
I now use 2 computers with BunqDesktop, and I need to copy the rules from one to another.

**Comment by Crecket** [comment]
Currently you can only export them one at a time but I'll add a button to export them all in the next release.
Clicking the menu icon at the top right of a category rule will show the export option for that specific item.

![image](https://user-images.githubusercontent.com/7481136/39366619-bbc0dd88-4a34-11e8-9ca9-3df502a40823.png)

Also, if you open the settings page you can change and/or copy the settings file location which contain your categories and category rules.

Personally I changed the location to my Google Drive folder so it automatically gets synced to my other devices
