### ISSUE TITLE
Help with translation

### ISSUE THREAD

**Issue by s-john19** [BunqCommunity/BunqDesktop#197]
I'm using the german version and there are some words not translated. Is there any easy way I can help you with that or do I need to open an issue any time I found one?

**Comment by Crecket** [comment]
We already have a user who is willing to translate so we'll try to get everything translated for the next version which I'm hopefully going to release this week 👍

**Comment by Crecket** [comment]
Just to notify you on this, the new version should contain all the German translations now 👍

**Comment by s-john19** [comment]
@Crecket Nice, thanks :) But if I found a wrong translation should I open a issue again or is there an easier way for you? :)
