### ISSUE TITLE
Exports

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#20]
Maybe a Idea to create different payment exports? To CSV,  PDF, MT940.. 
Also a export with a single "payment report"/"proof of payment".

This endpoint van be used: https://doc.bunq.com/api/1/call/customer-statement-export

**Comment by DennisSnijder** [comment]
@basst85 thanks for reporting the issue!
This is something we want to add for sure!

**Comment by basst85** [comment]
@DennisSnijder Is there already a simple roadmap, so in dont report any wishes that are on that map/list ☺️

Like:
- Create payment
- Create request
- Exports
- Schedule payment
- Import payments from CSV or Xlst 
...

**Comment by basst85** [comment]
I mean .XLS off course ☺️

**Comment by DennisSnijder** [comment]
Yes, we should create a roadmap for sure!

**Comment by basst85** [comment]
@DennisSnijder do you maybe have a Telegram group or Slack channel? ☺️

**Comment by DennisSnijder** [comment]
@basst85 
We just created a telegram group 😊 feel free to join!
https://t.me/joinchat/G_JrZg8BxNdIOsQS1TfY3A
