### ISSUE TITLE
Updating to the newest version

### ISSUE THREAD

**Issue by s-john19** [BunqCommunity/BunqDesktop#201]
I downloaded the new 0.8.5 exe Update but the installation stops with this error: 
![image](https://user-images.githubusercontent.com/36280159/40017584-1a9351d2-57ba-11e8-9c04-d72269e6147f.png)

**Comment by Crecket** [comment]
Which OS are you currently on?

**Comment by s-john19** [comment]
Windows 10 1803

**Comment by s-john19** [comment]
Ok I removed all files from bunqdesktop, installed the new 0.6 version and it is working now.

**Comment by Crecket** [comment]
Alright 👍
