### ISSUE TITLE
Filter events based on excluding categories

### ISSUE THREAD

**Issue by MrLuit** [BunqCommunity/bunqDesktop#204]
**Is your feature request related to a problem? Please describe.**
Sometimes it's really hard to differentiate between different colors if you have too many categories in the category transaction history graph

**Describe the solution you'd like**
Make it optional to exclude certain categories from the category transaction history graph

**Describe alternatives you've considered**
- Use less categories (not really an option since I love the cateogries)

**Additional context**
Here's an example of my problem:
![](https://i.imgur.com/P5lrFZZ.png)
It would be way better to let the user pick which categories are used for making the graph

**Comment by Crecket** [comment]
Sounds reasonable enough 👍 I think the best solution would be to add a whitelist/blacklist mode where you can choose to either exclude or include certain categories

**Comment by Crecket** [comment]
You can now filter by category and then switch between Including the categories and showing nothing else. Or excluding the categories and showing everything else.
