### ISSUE TITLE
Add recipient name/sender name to rule type

### ISSUE THREAD

**Issue by MrLuit** [BunqCommunity/BunqDesktop#206]
**Is your feature request related to a problem? Please describe.**
It takes a lot of time to properly categorize all of your transactions

**Describe the solution you'd like**
It would be great to have two extra rule types called 'Recipient/sender' and 'Transaction description'. For example; you could create a new rule that automatically categorizes any purchase from store X as grocery shopping.

Another example: tag all transaction to Paypal as online purchases.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by Crecket** [comment]
You should be able to do both of these using the Value Rule and then selecting Description, Iban or Display name.

**Comment by MrLuit** [comment]
Yup, that works. Thanks!
