### ISSUE TITLE
Small visual bug when viewing transaction

### ISSUE THREAD

**Issue by MrLuit** [BunqCommunity/BunqDesktop#218]
## Checklist before submitting
 - [x] You are using the latest version that is currently available.
 - [x] The API key you are using is correct for the environment you selected. So you are not using a developer key with the production environment.
 - [x] Your API key is a wildcard API key OR the IP you are currently on is whitelisted for the API key you entered.
 - [x] Development: You updated your dependencies.
 - [x] Development: The branch you are building has merged the latest changes from the master branch.

## Information

![](https://i.imgur.com/wRFgLBe.png)

Windows 10, Bunq Desktop 0.8.7

**Comment by Crecket** [comment]
Fixed 👍 thanks for the report
