### ISSUE TITLE
Remove the native frame around the application

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#23]

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/31788188-4d893a74-b50e-11e7-99d3-2308b7253e0b.png)

**Comment by ntimo** [comment]
@Crecket this looks awesome +1

**Comment by basst85** [comment]
@Crecket Looks nice! but now you cant minimize and maximize the screen?
