### ISSUE TITLE
Disable create account functionality when 25 accounts exist

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/bunqDesktop#232]

**Comment by OGKevin** [comment]
Well, after you unlock/buy the 25 extras you can still create new accounts tho 🤔  so a full disable is not user friendly.

**Comment by OGKevin** [comment]
@basst85 what does card limit have to do with this ? 😉 but i think it does.

**Comment by basst85** [comment]
@OGKevin Whoops, LOL! I mean IBAN activation limit

**Comment by Crecket** [comment]
@OGKevin It'd be better to simply warn the user than? I'm not sure how getting more accounts is billed but I'm guessing it happens as soon as you create the account?

**Comment by OGKevin** [comment]
@Crecket AFAIK you can only do that via the app and not via the pub API. But you can always confirm in sandbox 😁
