### ISSUE TITLE
Monetary account balance not updating

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#24]
The account balance is not updating after a restart of the app. It's only updating when switching user and login again.

**Comment by Crecket** [comment]
Is this happening on the current release or development app? I fixed a bunch of the issues with data not loading properly on the current master branch

**Comment by basst85** [comment]
In development it's working better now, account balances are updating after restart app.
But it is not updating when i click on a account (payments list is updating but not the account balances).

**Comment by Crecket** [comment]
Ah I completely forgot about that, I only added the proper triggers to load on startup but clicking a account only loads the payments
