### ISSUE TITLE
Missing split/request in bunqDesktop

### ISSUE THREAD

**Issue by moorlag** [BunqCommunity/bunqDesktop#245]
**Using split/request**
I'm missing the option to request money. It's a feature I use a lot in the app.

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/44633256-f3755700-a988-11e8-98c8-ef2c9377810f.png)

You can now split payments using the same system as the bunq app or disable it and send everyone a request for the full amount like before
