### ISSUE TITLE
Checksum for brew failing

### ISSUE THREAD

**Issue by krummler** [BunqCommunity/bunqDesktop#246]
Hi there,

I'm trying to install the app through Homebrew on OSX (High Sierra, 10.13.5). The installion fails as the checksum doesn't seem to be correct? I'm running Homebrew 1.7.0.

Installing does mention `running "brew update" may fix sha256 checksum errors`. However, running update tells me i'm already up-to-date.

```
brew cask install bunq
==> Satisfying dependencies
==> Downloading https://github.com/BunqCommunity/BunqDesktop/releases/download/0.8.11/BunqDesktop-0.8.11.dmg
Already downloaded: /Users/user/Library/Caches/Homebrew/Cask/bunq--0.8.11.dmg
==> Verifying checksum for Cask bunq
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'bunq' does not match.

Expected: cda59e4653e747c0099c5078aaf5d59040d68f7f5784b5a6d94a6fcfff45d9b3
Actual:   ff461b377e5b6acd9bffd86e2c8367eb3ec2e1e6734c8a64f58ef4b8aed3eb05
File:     /Users/user/Library/Caches/Homebrew/Cask/bunq--0.8.11.dmg

To retry an incomplete download, remove the file above.
```

**Comment by Crecket** [comment]
We ran a hotfix and since I'm currently on holiday I didn't notice right away that our PR was held back. It should get accepted soon. So no security issue is going on right now, just outdated checksum values.

https://github.com/Homebrew/homebrew-cask/pull/49873

**Comment by Crecket** [comment]
It just got accepted so it should be working now 👍
