### ISSUE TITLE
Incorrect calculation for other currency

### ISSUE THREAD

**Issue by quatronic** [BunqCommunity/bunqDesktop#252]
See the attached screenshot. The transaction amount is not shown correctly (the 250 is USD, but there is a Euro sign before).

<img width="218" alt="screen shot 2018-08-07 at 07 14 18" src="https://user-images.githubusercontent.com/34214368/43755741-b7084074-9a11-11e8-978f-64866dec3976.png">

**Comment by Crecket** [comment]
Fixed in #249, thanks for the report
