### ISSUE TITLE
Category-rule editor feedback after saving

### ISSUE THREAD

**Issue by L00Cyph3r** [BunqCommunity/bunqDesktop#257]
This morning I figured there was this awesome feature of adding categories to transactions based on rules.
After fiddling around I clicked on save, but it seemed like nothing happened. It did save my rule in the background, but I couldn't know since I did not get any feedback about the save-progress, nor was I taken back to the rules-overview-page to see my new rule.

I would suggest giving some sort of feedback after you saved a rule, either by changing the text/color of the save-button, a notification or being taken back a screen.

**Comment by Crecket** [comment]
The page now displays a notification that the changes were saved 👍
