### ISSUE TITLE
Show message history / add message to transaction

### ISSUE THREAD

**Issue by L00Cyph3r** [BunqCommunity/bunqDesktop#260]
I don't know for sure if this isn't already on any list, but is there a way to display the notes that you can add from the app (and/or attachments) in the transaction-details page.

I can imaging that attachment could be a bit of a hassle, but at least showing the texts and being able to add a comment to a transaction would be very welcome.

**Comment by OGKevin** [comment]
The public api does not allow for you to get the notes AFAIK.

**Comment by Crecket** [comment]
Like Kevin said that endpoint isn't supported by the public API

**Comment by L00Cyph3r** [comment]
Too bad :disappointed: 

Next question was if we could somehow save extra fields to a transaction on the bunq-side, so labels and other information would be accessible from multiple devices. Guess it's time for the waiting-game.
