### ISSUE TITLE
Show banner when in sandbox mode

### ISSUE THREAD

**Issue by painjansen** [BunqCommunity/bunqDesktop#266]
# Context

This is a quick note from the bunq team and mostly a feature request. Today someone contacted us with an urgent question about privacy. He was claiming to see someone else's account information through bunq desktop. After a few minutes we found out he was looking at sandbox data. 

# Solution

A very easy fix could be to always show a banner when you're in sandbox mode. The banner can say something like 'You're currently seeing test information, wanna go pro?'

**Comment by L00Cyph3r** [comment]
@painjansen Please let me know if the change in #269 is sufficient enough.

**Comment by painjansen** [comment]
looks amazing @L00Cyph3r 👍
