### ISSUE TITLE
Show local date/time, instead of UTC

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#27]
The UTC datetime is now visible in the payments overview (and payment info), not the datetime of the local (machine) timezone. 

Maybe also use the locale settings for currency value?

**Comment by Crecket** [comment]
What would be the preferred format when displaying dates? And any date with a year that is older than the current year will display the year as well.
![image](https://user-images.githubusercontent.com/7481136/31823520-acf4bc38-b5ac-11e7-9940-b528eecbd529.png)

**Comment by basst85** [comment]
Yes that looks nice. But maybe some people want a other date format, like "September 4 10:13:30 PM" or "04.09.2017 22:13:30" (date format in Germany). 

Maybe you can use the local system date format?

**Comment by Crecket** [comment]
#29

**Comment by basst85** [comment]
@Crecket You can also use moment.js ☺️

**Comment by Crecket** [comment]
Moment.js is quite big so I'd rather not include it unless we're doing more than basic date formatting

**Comment by DennisSnijder** [comment]
@basst85 I suppose we can close this now? 😄

**Comment by Crecket** [comment]
This seems to work and is now available in the master branch 👍
