### ISSUE TITLE
Mastercard payment(s) are reported as Maestro payments in the stats overview (and the other way around))

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#277]
I'm new to bunqDesktop and I tried this on Windows, version 0.8.11.

In the acount overview the payment type is correct, but in the stats overview the payments of Mastercard and Maestro are switched around.

For example, see my screenshot of the lonely Mastercard payment I made on August 13th from the accounts overview, and the screen shot where this is listed as a Maestro payment in the Stats view.
![mastercard20180813](https://user-images.githubusercontent.com/23123995/44651467-c7d68900-a9e9-11e8-97fa-c28e4294f1f6.png)
![stats](https://user-images.githubusercontent.com/23123995/44651476-cc02a680-a9e9-11e8-9674-bd4adebd8070.png)

**Comment by Crecket** [comment]
Is this still occuring in the latest nightly build? I can't seem to reproduce this issue

**Comment by JeroenEeuwes** [comment]
Yes, it still occurs in the build from last night.
![mastercard](https://user-images.githubusercontent.com/23123995/44809947-7c320400-abd0-11e8-970c-ec1391fe137f.png)
![stats](https://user-images.githubusercontent.com/23123995/44809948-7c320400-abd0-11e8-9146-d40a42ba8f3f.png)

This is the debug info:

{
	"id": 17807007,
	"created": "2018-08-13 19:26:21.938714",
	"updated": "2018-08-13 23:39:05.351606",
	"monetary_account_id": 918254,
	"card_id": 311886,
	"card_authorisation_id_response": "0QJ0BT",
	"amount_local": {
		"currency": "EUR",
		"value": "2.71"
	},
	"amount_billing": {
		"currency": "EUR",
		"value": "2.71"
	},
	"amount_original_local": {
		"currency": "EUR",
		"value": "2.71"
	},
	"amount_original_billing": {
		"currency": "EUR",
		"value": "2.71"
	},
	"amount_fee": {
		"currency": "EUR",
		"value": "0.00"
	},
	"decision": "ALLOWED",
	"decision_description": "",
	"decision_description_translated": "",
	"description": "WWW.ALIEXPRESS.COM INTERNET, GB",
	"authorisation_status": "AUTHORISED",
	"authorisation_type": "NORMAL_AUTHORISATION",
	"city": "INTERNET",
	"alias": {
		"iban": "NL28BUNQ2206901366",
		"is_light": false,
		"display_name": "J.W.B. Eeuwes",
		"avatar": {
			"uuid": "0e2c27ec-46a1-49d3-ac44-80351c87eed3",
			"image": [
				{
					"attachment_public_uuid": "85ec63f6-5af9-4027-b499-614d6ca6f6ea",
					"height": 808,
					"width": 808,
					"content_type": "image/jpeg"
				}
			],
			"anchor_uuid": null
		},
		"label_user": {
			"uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e",
			"display_name": "J.W.B. Eeuwes",
			"country": "NL",
			"avatar": {
				"uuid": "bc547d38-4b7a-48ef-82a8-1a087a65c943",
				"image": [
					{
						"attachment_public_uuid": "da16e27a-df7d-418f-9309-3c5aef5e1599",
						"height": 385,
						"width": 385,
						"content_type": "image/jpeg"
					}
				],
				"anchor_uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e"
			},
			"public_nick_name": "Jeroen"
		},
		"country": "NL"
	},
	"counterparty_alias": {
		"iban": null,
		"is_light": null,
		"display_name": "WWW.ALIEXPRESS.COM",
		"avatar": {
			"uuid": "626142d8-1c47-4814-9604-89aefe369e10",
			"image": [
				{
					"attachment_public_uuid": "45373270-dcdc-41ef-941e-ae69d1a17506",
					"height": 640,
					"width": 640,
					"content_type": "image/jpeg"
				}
			],
			"anchor_uuid": null
		},
		"label_user": {
			"uuid": null,
			"display_name": "WWW.ALIEXPRESS.COM",
			"country": "GB",
			"avatar": null,
			"public_nick_name": "WWW.ALIEXPRESS.COM"
		},
		"country": "GB",
		"merchant_category_code": "5964"
	},
	"label_card": {
		"uuid": "b859b51d-a729-4b1f-afe0-c1326be55353",
		"type": "MASTERCARD",
		"second_line": "Mastercard",
		"expiry_date": "2022-08-31",
		"status": "ACTIVE",
		"label_user": {
			"uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e",
			"display_name": "J.W.B. Eeuwes",
			"country": "NL",
			"avatar": {
				"uuid": "bc547d38-4b7a-48ef-82a8-1a087a65c943",
				"image": [
					{
						"attachment_public_uuid": "da16e27a-df7d-418f-9309-3c5aef5e1599",
						"height": 385,
						"width": 385,
						"content_type": "image/jpeg"
					}
				],
				"anchor_uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e"
			},
			"public_nick_name": "Jeroen"
		}
	},
	"token_status": null,
	"reservation_expiry_time": null,
	"applied_limit": "CARD_LIMIT_POS_ICC",
	"allow_chat": true,
	"pan_entry_mode_user": "E_COMMERCE",
	"eligible_whitelist_id": 184339,
	"secure_code_id": null,
	"wallet_provider_id": null,
	"request_reference_split_the_bill": []
}

**Comment by JeroenEeuwes** [comment]
It's still the same problem in Nightly build 2018-08-29 23:06:14.

**Comment by JeroenEeuwes** [comment]
I don't know anything about JavaScript, but in the [stats.worker.js](https://github.com/BunqCommunity/bunqDesktop/blob/master/src/react/WebWorkers/stats.worker.js) I saw these two fragments
![github](https://user-images.githubusercontent.com/23123995/44834161-9bf91480-ac30-11e8-82d4-6f8dfec33ac0.png)
and I'm guessing this is why the Maestro amount is shown as MasterCard and vice versa.
