### ISSUE TITLE
Account image/photo doesn't show or is shown different than the bunq app

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#281]
I'm new to bunqDesktop. i'm using it on Windows, version 0.8.11.

I have several accounts. 1 account is missing the image/photo:
![accountphoto](https://user-images.githubusercontent.com/23123995/44653610-89dc6380-a9ef-11e8-9cda-2d1411d6e9c8.png)

There is some kind of small white square which isn't the actual image/photo selected. This happens to be the last account, don't know if that really matters. My wild guess of the problem is that the image I used is too large.

Note that the image shown in bunqDesktop is different than in the bunq app. The app selects the middle square of the image. So if you used a non square picture some bits fall of. In the above screen shot you can see this with the picture of the car. The app chops off some parts of both the left and right side, but bunqDesktop shows the entire width and adds a bit of grey on the bottom and top.

**Comment by JeroenEeuwes** [comment]
Thanks for letting me know. I did try to find an old issue on GitHub, but couldn't find any (which does not exclude poor searching skills on my part).

**Comment by Crecket** [comment]
The other image had a more technical title which is why you didn't find it most likely :)

**Comment by JeroenEeuwes** [comment]
Thanks. Does this mean the minor issue about the different view of a non-square image is OK? Or do you want a new issue?

**Comment by Crecket** [comment]
Does the bunq app display those images as circles? I think they might be setting a white background instead of scaling the image but I'll have to check that to be sure

**Comment by JeroenEeuwes** [comment]
No, it is a square in the bunq App. I'm very bad at photoshop but I took a screenshot on my phone and tried to zoom in on my PC to make it more clear (at least I hope so).
![square](https://user-images.githubusercontent.com/23123995/44660654-9e792580-aa08-11e8-81ba-6f21cbdf5a45.png)
In the app there sides are chopped off, the image is sort of zoomed in. In bunqDesktop there is "empty room" on the top and bottom.

it's a bit like showing a widescreen movie on an old TV. You either have a black band on top and bottom or you are missing the left and right part of the picture. On it's own both choices can be valid but it's just that bunq app does it different than bunqDesktop.

**Comment by Crecket** [comment]
Mhm I think their way is slightly more robust since simply setting a background color would still look odd if the image itself has a different background color. So I guess I'll use the same strategy to display them

Thanks for checking 👍
