### ISSUE TITLE
Indication when a filter is active

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#282]
I'm new to bunqDesktop, I'm using version 0.8.11 on Windows.

I had been playing with filters on the Stats view. When you go back to the account view the filters remain active, but I didn't know. So I was missing a lot of transactions all of a sudden and it took a while for me to find out the filter I entered on the Stats view was still active. 

Perhaps an indicator somewhere to let users know a filter is active is more user friendly? I'm not a UX designer, but between the text "payments and requests" and the information icon & filter icon seems to be a very big space where something like "filter active" could be shown.

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/44732441-9216ca80-aae5-11e8-94f5-e391d7a5f5fa.png)
It now shows how many of the total events are shown at the top of the events list
