### ISSUE TITLE
Select which accounts are used in the total balance

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#284]
I'm using the Nightly build 2018-08-26 23:05:54 on Windows.

In the bunq App you can select which accounts are used in the total balance. So for instance you have an account A with 100 euro, account B with 50 euro and account C with 250 euro. Normally the total balance would be shown as 400 euro. If you deselect account C the total amount would be shown as 150 euro.

I couldn't find where this is possible in bunqDesktop so it always shows the total amount of all accounts.

**Comment by Crecket** [comment]
I was planning on adding this but I haven't created an issue for it yet so thanks for the suggestion 👍
