### ISSUE TITLE
Amounts in the account overview

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#285]
I'm using Nightly build 2018-08-26 23:05:54 on Windows.

In the accounts the amounts that are added to my account are shown in green and amounts that are deducted are shown in red. For some users this is confusing because they are color blind, and  red-green is the most common. Can a minus be added to amounts that are deducted?

In the bunq app the minus is shown and they use blue/orange just like the request/pay buttons.

Also, I find it cleaner to leave off the euro for every amount (just like the bunq app). You can't have any other currency anyway.

**Comment by L00Cyph3r** [comment]
> Also, I find it cleaner to leave off the euro for every amount (just like the bunq app). You can't have any other currency anyway.

Is that also true for internatial Mastercard-payments? Because I sometime get the option to pay either in euro's or dollars (with paypal at least).
Anyways, I think it's quite easy to add a currency-symbol if it's not in euro's, just for safety.

**Comment by JeroenEeuwes** [comment]
According to bunq they only support SEPA transfers which are always in euro (see [here](https://together.bunq.com/d/2932-make-a-sepa-transfer-to-a-non-euro-account-such-as-uk-%C3%82%C2%A3) for example).

**Comment by ntimo** [comment]
I think using the colors that bunq uses would be good in this case. What do you think @Crecket ?

**Comment by Crecket** [comment]
@ntimo I prefer the current colors over the ones bunq uses to be honest.

The outgoing payments should show a minus sign now and I'm testing how the amounts will look without the currency symbols.

**Comment by L00Cyph3r** [comment]
I know the colour-blind audience is quite limited, and the whole colour scheme of bunq would only look weird I can imagine. How about adding a switch in the settings that allow a colourblind-mode?

If you don't like manual labour of changing all the colours, let me know 😉
