### ISSUE TITLE
Negative amount does not follow regional conventions

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#288]
I asked for the minus sign in [this request](https://github.com/BunqCommunity/bunqDesktop/issues/285) for negative amounts. In the Nightly build 2018-08-27 23:04:54 this was changed. The minus sign is before the Euro sign which is not according to my regional settings. Below a screenshot of all the possibilities that Windows allows. My selection is the default for the Dutch region.

I know I did not ask to follow the regional settings, but only for a minus sign  :innocent:
Anyway, I think it would be better to follow the regional settings. In Linux this is the same, but then using the locale settings. I don't know how this works on MacOS.

This is the advise of the [Nederlandse Taalunie](https://taaladvies.net/taal/advies/vraag/1198/euro_12_12/) (in Dutch) about the place of the minus sign.

![negative](https://user-images.githubusercontent.com/23123995/44697558-a1adf900-aa7c-11e8-969b-ff743bde1d6a.png)

**Comment by basst85** [comment]
The region can be added as a header to the http request (X-Bunq-Region), how does the bunq API handle this?

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/44717741-2cfbae80-aabe-11e8-9001-36eaa4ae2425.png)
I modified it a bit to use the `nl` locale setting and it seems to use the same format now 👍
