### ISSUE TITLE
NaN Invalid Date, NaN  NaN:NaN:NaN

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#29]
After the last commit i get a lot of "NaN Invalid Date, NaN  NaN:NaN:NaN" in the payments list.
The date in the payment JSON is: "2017-10-20 12:16:40.797783"

I have also a payment with the date "5 November  12:9:44" (datetime in JSON is: "2017-10-11 11:09:44.933069")

**Comment by Crecket** [comment]
Huh that is odd :/ I'll disable it for now in the front-end until I can test this more
