### ISSUE TITLE
Dashboard overview shows all events and not only from the selected account

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#291]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

In the dashboard all events from all accounts are shown, even when 1 account is selected (in this case "pinrekening")
![bunqdesktop](https://user-images.githubusercontent.com/23123995/44769620-879c1580-ab65-11e8-9abf-d956dc09aded.png)

This is how it looks in my bunq App:
![screenshot_20180829-082934](https://user-images.githubusercontent.com/23123995/44769790-0ee98900-ab66-11e8-8669-7c19372b0cf9.jpg)

The first two events shown in bunqDesktop don't belong to "pinrekening"

**Comment by Crecket** [comment]
It intentionally shows all payments for all accounts, you can filter by account in the filter at the bottom.

I'll be reworking how this works since right now you have to manually click each account to fetch the payments.

**Comment by JeroenEeuwes** [comment]
What is the difference between the > and (i) icon? I thought that the > meant that that account was selected to show the events on the right.

**Comment by Crecket** [comment]
It used to be that only 1 account was selected, but right now that account is simply used as the default account when you go to the pay/request pages for example.

I plan on automatically updating the events for all accounts

**Comment by JeroenEeuwes** [comment]
right, that's possibly why I saw it working different than before. The > icon sort of implies (to me at least) that the events shown on the right are connected to that account. Perhaps some icon that does not imply a connection between the left hand an right hand side of the screen would be better?
