### ISSUE TITLE
No events shown at all

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#294]
I'm using Nightly build 2018-08-28 23:06:03 on windows.

Sometimes (but not always) no events are shown. This happens when I clicked on an event and return by clicking on the left arrow icon. Or when I clicked on a  (i) to go to the account view and go back with the left arrow icon.
![bunqdesktop-no-events](https://user-images.githubusercontent.com/23123995/44770376-23c71c00-ab68-11e8-9b19-3ee522f9967c.png)

**Comment by Crecket** [comment]
I added some performance improvements so it doesn't update the page as much. It looks like I went a bit overboard :p

**Comment by JeroenEeuwes** [comment]
I can confirm it shows no events very fast and efficient! ;p

**Comment by JeroenEeuwes** [comment]
Something is not working OK with the event counter too. I have put the paging on "1" to "All".

Then it says 43 events in the Dashboard. When I go to an account (using the (i) icon) and back it will say 57. When I select an account again and go back it will way 72 or 73. Sometimes it says 105. I don't know on top of my head how many events I've got so I don't know the correct number. it does not seam to matter which account I use. It doesn't always change either.
