### ISSUE TITLE
Wierd Mastercard event shown

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#295]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

There is a wierd Mastercard Tap & Pay event shown in the event overview. I've never used the tap&pay feature of my Mastercard. I did use my Mastercard to pay 10 euro to send a parcel with DHL. I guess those are somehow related.
![bunqdesktop-strange-event](https://user-images.githubusercontent.com/23123995/44770507-90421b00-ab68-11e8-9751-8c2461d6f3b6.png)

This shows up when I click on the Mastercard event:
![mastercard-event](https://user-images.githubusercontent.com/23123995/44770523-9d5f0a00-ab68-11e8-9347-3d393a9249e7.png)

This event doesn't show in the bunq app on my phone:
![screenshot_20180829-072513](https://user-images.githubusercontent.com/23123995/44770568-bcf63280-ab68-11e8-8cf6-4b647efc27b0.jpg)

**Comment by Crecket** [comment]
The payment amount should be fixed now but I'm not sure why it is showing tap & pay as the payment type. Could you go to the debug screen and post that information here or send it to me in private on the telegram channel?
![image](https://user-images.githubusercontent.com/7481136/44785801-669de980-ab92-11e8-8a64-96427d617c79.png)

**Comment by JeroenEeuwes** [comment]
@Crecket I don't think there is much personal information in there (although i'm not 100% sure). Anyway, this is the debug info:

{
	"id": 18196131,
	"created": "2018-08-28 10:43:54.327180",
	"updated": "2018-08-28 10:43:58.540235",
	"monetary_account_id": 918254,
	"card_id": 309721,
	"card_authorisation_id_response": "W3AT8C",
	"amount_local": {
		"currency": "USD",
		"value": "0.00"
	},
	"amount_billing": {
		"currency": "EUR",
		"value": "0.00"
	},
	"amount_original_local": {
		"currency": "USD",
		"value": "0.00"
	},
	"amount_original_billing": {
		"currency": "EUR",
		"value": "0.00"
	},
	"amount_fee": {
		"currency": "EUR",
		"value": "0.00"
	},
	"decision": "ALLOWED",
	"decision_description": "",
	"decision_description_translated": "",
	"description": "Mastercard St. Louis, US",
	"authorisation_status": "PENDING",
	"authorisation_type": "NORMAL_AUTHORISATION",
	"city": "St. Louis",
	"alias": {
		"iban": "NL28BUNQ2206901366",
		"is_light": false,
		"display_name": "J.W.B. Eeuwes",
		"avatar": {
			"uuid": "0e2c27ec-46a1-49d3-ac44-80351c87eed3",
			"image": [
				{
					"attachment_public_uuid": "85ec63f6-5af9-4027-b499-614d6ca6f6ea",
					"height": 808,
					"width": 808,
					"content_type": "image/jpeg"
				}
			],
			"anchor_uuid": null
		},
		"label_user": {
			"uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e",
			"display_name": "J.W.B. Eeuwes",
			"country": "NL",
			"avatar": {
				"uuid": "bc547d38-4b7a-48ef-82a8-1a087a65c943",
				"image": [
					{
						"attachment_public_uuid": "da16e27a-df7d-418f-9309-3c5aef5e1599",
						"height": 385,
						"width": 385,
						"content_type": "image/jpeg"
					}
				],
				"anchor_uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e"
			},
			"public_nick_name": "Jeroen"
		},
		"country": "NL"
	},
	"counterparty_alias": {
		"iban": null,
		"is_light": null,
		"display_name": "Mastercard",
		"avatar": {
			"uuid": "37d3c30d-2b19-4860-a1ca-513a43d29a4c",
			"image": [
				{
					"attachment_public_uuid": "9e218a94-99a9-4507-b2f2-b2c6f6891697",
					"height": 640,
					"width": 640,
					"content_type": "image/jpeg"
				}
			],
			"anchor_uuid": null
		},
		"label_user": {
			"uuid": null,
			"display_name": "Mastercard",
			"country": "US",
			"avatar": null,
			"public_nick_name": "Mastercard"
		},
		"country": "US",
		"merchant_category_code": "5969"
	},
	"label_card": {
		"uuid": "5ed5362a-e036-4085-bc58-30582196cf04",
		"type": "MAESTRO_MOBILE_NFC",
		"second_line": "Tap & Pay Maestro",
		"expiry_date": "2022-08-31",
		"status": "ACTIVE",
		"label_user": {
			"uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e",
			"display_name": "J.W.B. Eeuwes",
			"country": "NL",
			"avatar": {
				"uuid": "bc547d38-4b7a-48ef-82a8-1a087a65c943",
				"image": [
					{
						"attachment_public_uuid": "da16e27a-df7d-418f-9309-3c5aef5e1599",
						"height": 385,
						"width": 385,
						"content_type": "image/jpeg"
					}
				],
				"anchor_uuid": "e9330ad1-015a-494a-ab67-d2861cb39d2e"
			},
			"public_nick_name": "Jeroen"
		}
	},
	"token_status": "ACTIVE",
	"reservation_expiry_time": null,
	"applied_limit": "CARD_LIMIT_UNSAFE",
	"allow_chat": true,
	"pan_entry_mode_user": "UNSAFE_E_COMMERCE",
	"eligible_whitelist_id": null,
	"secure_code_id": null,
	"wallet_provider_id": "420",
	"request_reference_split_the_bill": []
}

**Comment by Crecket** [comment]
Err that is really strange, could you maybe have bunq support check that? It looks like a normal payment and it definitely says "Tap & Pay Maestro" so I'm not sure why the API is returning it

**Comment by JeroenEeuwes** [comment]
I'll ask them and let you know

**Comment by JeroenEeuwes** [comment]
@Crecket bunq support thinks it's the activation of Tap&Pay on my phone. He's think their app filters this out because of the 0.00 "payment". He wants to know if he should ask the API team to be sure and let me know or if it would be easier if you ask their API team.

**Comment by Crecket** [comment]
Hm well bunqDesktop tends to display more events than the bunq app, so that might be it than. Thanks for checking
