### ISSUE TITLE
Account overview doesn't show joint account information

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#298]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

In the Account overview there is no indication when an account is a joint account. In the Dashboard overview you can see this with the two person orange icon. 
It also doesn't show the name of the other joint account holder; it even says the account is not shared. While I think that is technically correct (sharing is not the same as a joint account) it is a bit confusing. 

In the bunq App the other account holder is named under the heading "Co-Owner". If you want a screen shot of that, please let me know

![dashboard-icon](https://user-images.githubusercontent.com/23123995/44775315-a4404980-ab75-11e8-9e84-e104dac2c1fc.png)
![joint-account](https://user-images.githubusercontent.com/23123995/44775318-a5717680-ab75-11e8-97b0-f8cf1da2b8a4.png)

**Comment by JeroenEeuwes** [comment]
Thanks, it shows more information. It only shows the first name though, can you change this to the full name?

**Comment by Crecket** [comment]
Ah yes fair enough, I used the public nickname but for this use case the full name is probably better 👍
