### ISSUE TITLE
Rules preview matches all events when adding a new value check rule

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#299]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

When you add a value check rule then all the events are automatically matched in the preview. I guess because all events match the value "empty" or null somehow. 

When you start typing the actual value this is not updated so all events keep showing as matched.

This resets to the correct matching when you press the save button or hide and show the preview again.

I'd rather not have all events automatically matched using a null/empty value. 

I'm not sure what the best way to deal with this is. It might not be efficient to recalculate every time some character is typed.

**Comment by Crecket** [comment]
Like you said at the end, I don't update the list because it starts to reduce performance when I update the event list on every keystroke. 

And I'm guessing the events all match with an empty value because you're using the Contains filter type

**Comment by L00Cyph3r** [comment]
How about a timeout after someone is done typing? Let's say after 1000ms of any typing-activity, update the list? This way there is more feedback about the matches, without affecting performance to much.
