### ISSUE TITLE
Add new rule from event view

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#300]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

It would be great if you could add a rule when in the event view. You can already add a category by hand, but that is only for the current event. I'd like to add a rule to an existing or new rule set. 

Perhaps even with the description pre-entered into a value check rule. Or some way for the user to choose which field/amount/iban and so on to be pre-entered in the rule?

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/46298746-23270880-c5a0-11e8-91e9-566a54c9e277.png)
Quick filter creation 👍
