### ISSUE TITLE
Direct debit is shown as normal payment

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/BunqDesktop#305]
I'm using Nightly build 2018-08-28 23:06:03 on windows.

A direct debit is shown in the bunq app as "direct debit paid". In bunqDesktop this is shown as "Sent payment with bunq", which is identical to payments I mande myself. It would be nice if it was shown as direct debit in bunqDesktop too.

**Comment by OGKevin** [comment]
Could you please provide some screenshots of course you can mask out details. The way the app an Bunq desktop gets its data is a lil different. The screenshots should give me a better idea.

**Comment by JeroenEeuwes** [comment]
This is bunq app:
![screenshot_20180829-212637](https://user-images.githubusercontent.com/23123995/44810604-79d0a980-abd2-11e8-9bff-47b02707e4bb.jpg)

This is bunqDesktop:
![directdebit](https://user-images.githubusercontent.com/23123995/44810492-20687a80-abd2-11e8-8819-18c43450df28.png)

**Comment by OGKevin** [comment]
Yea, @crecket as ive told you in PM, the app is showing the request response here and you are showing the mutation. That’s the diff.

**Comment by Crecket** [comment]
It now shows the Requests (E.G. Direct debits and iDeal payments) instead of the regular Payment objects. So I'll keep this issue open until some more people have tested it with the next nightly build

**Comment by JeroenEeuwes** [comment]
It looks OK for me now.
