### ISSUE TITLE
Can't resize window from top / title bar

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#306]
I'm using Nightly build 2018-08-28 23:06:03 on WIndows.

You can't resize the window from the top. You can resize from left, right and bottom (and the bottom corners). Resizing from the top or top corners does not work. Actually you can't resize on left or right either when the mouse is on the title bar. So I guess it has something to do with the title bar.

**Comment by L00Cyph3r** [comment]
I can drag from the top-right corner, but not in the location you'd expect:

![image](https://user-images.githubusercontent.com/10772371/44811406-ef3d7980-abd4-11e8-85aa-5dfdfa08eadd.png)

**Comment by JeroenEeuwes** [comment]
Ah, I see. It works above the three icons. It also works in the corner on the left, if you move he cursor to exactly the right spot.

Anyway, it would be nice if it would work on the entire top and actually in the corner.

**Comment by Crecket** [comment]
This is native behavior for Electron with the non-native frame we use so I can't easily change this. If you really want that to work

**Comment by JeroenEeuwes** [comment]
Thanks. I found where this was hidden. One small nitpick: when you change the setting to use native frame it says that the application has to be restarted to activate this. But at the same time the exit button (and minimise and maximise too) were hidden. Of course Ctrl-W worked, but I think it would be better to leave these three buttons in place until the application was closed.
