### ISSUE TITLE
Minus sign for negative amount is not shown in event view

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#307]
I'm using on Windows.

In the event list a [negative amount](https://github.com/BunqCommunity/bunqDesktop/issues/285) has a [minus sign](https://github.com/BunqCommunity/bunqDesktop/issues/288). But this minus sign is not shown when you click on the event itself:
![directdebit](https://user-images.githubusercontent.com/23123995/44811204-4a22a100-abd4-11e8-830c-c46a2b15e7fa.png)

**Comment by JeroenEeuwes** [comment]
I'm using Nightly build 2018-08-29 23:06:14 on windows, but it still does not show the minus sign.
![bunqdesktop - request info](https://user-images.githubusercontent.com/23123995/44831286-2b4cfa80-ac26-11e8-9b3e-483ba4f9f4ce.png)

**Comment by Crecket** [comment]
Fixed this 👍 I was hiding the regular Payment objects and showing these Requests instead. And because of that the amount wasn't a 'negative' value so to speak
