### ISSUE TITLE
Option to remove/randomise personal data when copying debug info

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#308]
It would be nice if there was an option to remove or randomise personal data when copying debug info.

For example geolocation. Some people might not always want to give out the amounts, bank accounts, descriptions and so on. Now you have to go through the JSON yourself which is not always easy. Especially if you don't know what each field means when you're not a bunq API expert.

**Comment by Crecket** [comment]
There is now a anonymize button below the export dialog to switch between original and anonymized data
