### ISSUE TITLE
Check if we can create Linux releases

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#31]
Should be pretty straight forward using a VM. I already created an appimage using Ubuntu 16

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/31836184-af1c27da-b5d4-11e7-8515-d92261572629.png)
Ubuntu 16 release version 🎉

**Comment by Crecket** [comment]
The configuration is setup correctly in order to do this so anyone can create a release using a linux machine

**Comment by probonopd** [comment]
Can you please update to the latest version of `electron-builder`? The generated AppImage seems strange (it lacks the magic number that signals an AppImage). Likely this has been fixed in the latest electron-builder.

**Comment by Crecket** [comment]
I upgraded both electron and electron builder to the latest stable release

**Comment by Crecket** [comment]
This is included in the 0.6.1 release, could you test again? @probonopd

**Comment by probonopd** [comment]
Thanks for the update. Strangely it seems still to be missing the AppImage magic bytes, 0x414901 at offset 8.

**Comment by Crecket** [comment]
I'm running the default build command from electron-builder using the latest stable release so I'm not entirely sure what is causing this. Testing it on my Vm with Ubuntu 16.04.3 seems to work fine and it is correctly detected as an AppImage.

Any idea what is causing this?

**Comment by Crecket** [comment]
I haven't received any feedback/error reports on this issue from anyone else and I can't reproduce it myself so I'm closing this issue

**Comment by probonopd** [comment]
Unfortunately it is still wrong, it is missing the AppImage magic bytes, `0x414901` at offset 8:

```
me@host:~$ xxd bunqdesktop-0.7.4-x86_64.AppImage | head -n 1
00000000: 7f45 4c46 0201 0100 0000 0000 0000 0000  .ELF............
```

Rebuilding with the latest electron-builder _should_ fix this. Thanks.
