### ISSUE TITLE
Multiple category split in separate amounts

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#310]
I'm using Nightly build 2018-08-28 23:06:03 on Windows.

It's possible to add multiple categories to one event. It would be nice if you could make a split of the amount. As it is now the total amount is counted in each category. But you might want to be more specific and split one payment into several categories, each with it's own amount. For example a payment of 100 euro at a supermarket with 30 euro for kid (diaper, baby food), 10 euro for hobbies (magazine), 15 euro for gifts (wine) and 55 euro for food.

**Comment by Crecket** [comment]
A bit out of scope for the current category system, it'd require a pretty major rewrite and other components depend on how it works right now
