### ISSUE TITLE
Have I Been Pwned integration

### ISSUE THREAD

**Issue by ntimo** [BunqCommunity/bunqDesktop#312]
Hello 👋,
it would be very nice if bunqDesktop could search the password used to encrypt the local data in the https://haveibeenpwned.com/ database this would would enable bunqDesktop to warn users if they use a insecure password, that has appeared in a previous data breach. 

Have I Been Pwned provides a API for this:
https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

**Comment by Crecket** [comment]
I don't want to send web requests to random external services like that. It's the user's own responsibility to pick a good password
