### ISSUE TITLE
bunq.me request shows up even though it's already closed

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#313]
I'm using Nightly build 2018-08-29 23:06:14 on windows.

In the bunq.me view a request shows up which is already closed in the bunq app.

![bunq me requests](https://user-images.githubusercontent.com/23123995/44835240-eaf47900-ac33-11e8-8846-b28a743e24e7.png)
![screenshot_20180830-090138-1](https://user-images.githubusercontent.com/23123995/44835242-ec25a600-ac33-11e8-96fd-5ff733ceea6d.jpg)

**Comment by Crecket** [comment]
That is intentional on the bunq.me page, you can click the Eye icon to hide them again which is done by default

**Comment by Crecket** [comment]
Oh and the payment you see is 'cancelled', I changed the color a bit to avoid confusion around that

**Comment by Crecket** [comment]
It has a status "canceled" which means you deleted/cancelled it manually

**Comment by JeroenEeuwes** [comment]
Sure, I cancelled the request. But the payment was already made. So there is no cancelled payment, I would say.
