### ISSUE TITLE
Scheduled payments are not shown

### ISSUE THREAD

**Issue by JeroenEeuwes** [BunqCommunity/bunqDesktop#315]
I'm using Nightly build 2018-08-29 23:06:14 on windows.

The scheduled payment screen says there are none:
![scheduled payments](https://user-images.githubusercontent.com/23123995/44837244-64db3100-ac39-11e8-926b-005e53cb0f6c.png)

But actually there are:
![app](https://user-images.githubusercontent.com/23123995/44837317-98b65680-ac39-11e8-97f9-0b3feb4db46b.jpg)

**Comment by ntimo** [comment]
Did you try to reinstall it? Because for me with the same version they are showing up as they should.
