### ISSUE TITLE
WildCard API Key for BUNQ Sandbox environment

### ISSUE THREAD

**Issue by sankarcn** [bunqCommunity/bunqDesktop#319]
**Is your feature request related to a problem? Please describe.**
I am unable to get an Wild Card API Key. I need this in the sandbox environment to develop and test  a few API calls.
I am not sure if there is an option in Desktop App to set a API Key  as wildcard.
Please help me in this.

**Comment by Crecket** [comment]
Enabling the wildcard option for a sandbox account can be done in the sandbox Android app from bunq. It's not that can be done by the API
