### ISSUE TITLE
Scheduled payments - edit screen does not use timezone/summertime correction

### ISSUE THREAD

**Issue by Cheaternl** [bunqCommunity/bunqDesktop#320]
In the Scheduled payments the record shows, for instance a recurring scheduled payment at 13:00 on a specific day.
The edit screen however, shows 11:00

Possibly the edit screen does not use timezone?

**Comment by Crecket** [comment]
Probably caused by the UTC timestamps not being formatted in the correct timezone yes

**Comment by Cheaternl** [comment]
Also, make sure, when someone edits a value like 13:00 , it will be really 13:00 in perspective to the user, so with timezone included.  Not that 13:00, after saving will be 15:00 :-)
