### ISSUE TITLE
Account selection check boxes don't work when you switched the API key

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#327]
I'm using Nightly build 2018-09-09 23:10:30. When you switch the API key (because the one you were using is invalid due to you being somewhere else) then the account selection check boxes don't work any more.

The total balance is shown for all accounts.

If you exit bunqDesktop and start again everything works fine (it also remembers the check boxes from before so you don't have to reset them).

**Comment by Crecket** [comment]
Ah thanks for figuring this out! I created #322  but I couldn't reproduce it again

**Comment by JeroenEeuwes** [comment]
I saw it before, but couldn't reproduce it either. Today I found out why. I didn't saw [322](https://github.com/bunqCommunity/bunqDesktop/issues/322), because it was closed. I forgot to search in closed issues, sorry.

**Comment by Crecket** [comment]
No worries, you figured out what was causing it haha
