### ISSUE TITLE
IBANs are not visually formatted

### ISSUE THREAD

**Issue by readefries** [bunqCommunity/bunqDesktop#336]
I noticed that all IBANs are not visually formatted, and the UI shows the technical representation of an IBAN.

An IBAN should be displayed (and printed), with a space after every four characters.
I will try to fix this myself and send a PR.

**Comment by Crecket** [comment]
I already have this set up now so no need for a PR 👍

**Comment by readefries** [comment]
Awesome! Saves me digging in a 'foreign' language 👍
