### ISSUE TITLE
Changing a scheduled payment, changes the account

### ISSUE THREAD

**Issue by readefries** [bunqCommunity/bunqDesktop#340]
## Bug report
When I edit a previously created scheduled payment and save it, the account is changed to my first account.

I can't reproduce it 0.8.11, but it is on a check-out of master. So it could be regression.

**Comment by Crecket** [comment]
I think this is caused by the new account list where it used to only show scheduled payments for the selected account. Since there is no real "selected account" anymore it grabs the default

**Comment by Crecket** [comment]
I also modified the starting date to grab the time_next value. It would use the date on which it was originally created which causes a payment to be sent immediately which isn't very user friendly
