### ISSUE TITLE
Payments in foreign currencies are not shown correctly

### ISSUE THREAD

**Issue by pbruins84** [bunqCommunity/bunqDesktop#342]
## Bug report
Payments in foreign currencies are not shown correctly

Here the pin transactions are shown correctly in euro's in the app:
![image](https://user-images.githubusercontent.com/5555752/45825031-9358a300-bcf1-11e8-99b0-48ebe2d9d1b0.png)

But in bunqDesktop they are shown in the original currency (Hungarian Florints), but with the euro sign in front:
![image](https://user-images.githubusercontent.com/5555752/45825164-e599c400-bcf1-11e8-89d8-87e8726da13f.png)

**Comment by pbruins84** [comment]
It also does mess up the graphs on the stats page.

**Comment by Crecket** [comment]
Which version are you testing on? All those issues should already be fixed on the development build 👍

**Comment by pbruins84** [comment]
I'm running 8.11, but couldn't find a related issue.

**Comment by Crecket** [comment]
No problem than, some of these minor issues get fixed without an official GitHub issue.
