### ISSUE TITLE
Why is Analytics added?

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#36]
Why is Google Analytics added? And what user information can be tracked now? (Google account, bunq user ID, payment ID's?)

**Comment by DennisSnijder** [comment]
Google analytics is being added to track usage and to check on what version is being used.
We dont’t track the Bunq User ID, the user id we send to google analytics is self generated. We don’t have any intention to track any data which is served from the API due to privacy reasons.

**Comment by basst85** [comment]
Thanks for your response @DennisSnijder that's nice 👍🏻 In my opinion it's enough to only track version, user  language and OS on app start. And track that info anonymised ☺️
