### ISSUE TITLE
Not passing login-screen after OAuth

### ISSUE THREAD

**Issue by RosaEinhorn** [bunqCommunity/bunqDesktop#368]
After logging in using OAuth (in version 0.9.1)  I'm getting the "authentication succesfull" message, but cannot pass the login screen, it jumps back to the API-QR-code.

**Comment by Crecket** [comment]
Could you open the options and check if the API key field is filled? And if it's not there, could you check the logs again? It should be logging more data now so I can check where things go wrong more easily

**Comment by RosaEinhorn** [comment]
Can't really find an API-Key in the setting. Where exactly should I find it?
Is it the "BunqDesktop.production.log.txt" that you need to inspect?

**Comment by Crecket** [comment]
If you hit the little wrench on the login screen it should open a new section where it might display the API key

And yes that is the log file 👍

**Comment by Crecket** [comment]
If anyone else is running into this issue, it seems there is a bug on bunq's end for certain users. It is being checked now but for now there likely is nothing I can do.

**Comment by Crecket** [comment]
[Confirmed to still be broken](https://together.bunq.com/d/4024-the-item-you-requested-could-not-be-found-on-session-server-call/14)

**Comment by RosaEinhorn** [comment]
I'm also in a bunq-pack, which is confirmed to be another problem. :-(

**Comment by Crecket** [comment]
Yeah there are multiple issues around this where it tends to break for certain people. So for now I'm going to wait for bunq to properly fix this instead of adding workarounds which might get unnecessary later on.

If I hide Joint accounts now and do a release to make this work for OAuth, I'll have to do another release later on to re-enable them again which I'd rather not do

**Comment by Crecket** [comment]
Any idea if this is working now? @RosaEinhorn I don't have this issue myself so I can't test if this is still a thing

**Comment by Crecket** [comment]
Since this is still bugged I'm removing this from the 0.9.2 release for now

**Comment by Crecket** [comment]
https://together.bunq.com/d/5759-api-docs-bug-tracker/4

This seems to have been fixed 🎉

**Comment by OGKevin** [comment]
Well, @Crecket should we keep this open until we can verify that it has been fixed :P 

So @bluewalk @RosaEinhorn please give it a shot and let us know 😁

**Comment by bluewalk** [comment]
@OGKevin Will do when I get home

**Comment by Crecket** [comment]
This got fixed confirmed by another user who was having issues https://together.bunq.com/d/5759-api-docs-bug-tracker/9
