### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by KeizerDev** [BunqCommunity/BunqDesktop#37]
Move all strings to a translations file. This will also keep the codebase more clean

**Comment by Crecket** [comment]
https://github.com/yahoo/react-intl or https://github.com/i18next/react-i18next would be nice

**Comment by Crecket** [comment]
Translations are now done through the `translate` higher-order-component from `react-i18next`.

```JS
import { translate } from "react-i18next";

class App extends React.Component{
    render(){
        return this.props.t("translation_key")
    }
}

// wrap the component in the HOC with the first argument being a namespace
// for this project we always use `translations` as our namespace
export default translate("translations")(App);
```

I created a basic handler which loads translations from `src/react/Locales` and stores any missing keys in development mode.

To begin translating this project start by replacing texts using the solution shown above until all texts are added to the locale dictionary files
