### ISSUE TITLE
Monetary account already has a Connect with user with alias "x"

### ISSUE THREAD

**Issue by csvanleeuwen** [bunqCommunity/bunqDesktop#372]
Hi! I love the Bunq Desktop App! Especially because when adding users, I can customize exactly what they can do and can't do (for example: they can see the total balance, but they cannot do any payments).

First I shared one of my accounts with another person in the app, but then I found out the settings were limited. Then I removed that person from my accounts again.

When I now want to add that person via the Bunq Desktop App: I get this message:

_Something went wrong
We received the following error while sending your connect request:
Monetary account already has a Connect with user with alias "Floris".
Response-Id: e9a0ae03-3f7a-4750-bc79-5c64c255086a_

![image](https://user-images.githubusercontent.com/43956248/46606234-6e8b6a80-cafc-11e8-8514-640540217786.png)

I'm using this version: bunqDesktop
Version: 0.9.1 WINDOWS.

**Comment by Crecket** [comment]
This isn't something I can do much about within bunqDesktop I think, are you sure that account doesn't already have a Connect with 'Floris'?

**Comment by csvanleeuwen** [comment]
Yes I'm very sure! I've checked on both the app and the Desktop app.

**Comment by csvanleeuwen** [comment]
![image](https://user-images.githubusercontent.com/43956248/46607540-b496fd00-cb01-11e8-97e3-268d0461b7ac.png)

**Comment by csvanleeuwen** [comment]
Ho I closed the issue but that was by mistake!

**Comment by Crecket** [comment]
Could you check in the official bunq app to see if it shows anything there?

**Comment by csvanleeuwen** [comment]
In the official Bunq app it shows like this:
![image](https://user-images.githubusercontent.com/43956248/46608218-47389b80-cb04-11e8-99bb-69c6c8b99e83.png)

**Comment by Crecket** [comment]
It should work just fine looking at the screenshots you sent, could you contact bunq support using the response ID you received in the error? It doesn't seem to be caused by bunqDesktop right now but I'll leave this issue open for now

**Comment by Crecket** [comment]
Could you try again to add the connect through bunqDesktop and then give me the time and response ID? That way I can have someone check the logs without going through support

**Comment by csvanleeuwen** [comment]
Yes I tried today (12th of October) around 11:17
![image](https://user-images.githubusercontent.com/43956248/46860318-773bb380-ce10-11e8-853d-b44d67ae4fdb.png)

**Comment by Crecket** [comment]
Since the bunq app doesn't show an existing connect either I really can't figure out what this bug might be. 

I suspect it might be caused by one of the other status types that a Connect might have (CANCELLATION_PENDING, CANCELLATION_ACCEPTED, CANCELLATION_REJECTED) but than that should be visible in the bunq app since it requires a user interaction.

**Comment by OGKevin** [comment]
I would suggest @csvanleeuwen to contact support and show them this issue. Maybe an engineer working at bunq could see what's going on here.
