### ISSUE TITLE
Add a visual saving feature for each bank account

### ISSUE THREAD

**Issue by rbarisic** [bunqCommunity/bunqDesktop#376]
**Is your feature request related to a problem? Please describe.**
I would like to be able to visually see and set savings goals in the application.

**Describe the solution you'd like**
It could be a bar or ring in the bank account on the left side, so you have a visual incentive for saving money to different accounts.

**Additional context**
So far, bunq is the only digital bank as of now that allows you to truly budget your moneys into a plethora of actual IBAN Bank Accounts. Still, a basic saving goal for those accounts is missing.
I do understand that at the moment you are just trying to map the functionality of the API to your application 1:1, but this would be an awesome feature.

If you don't like the idea of features likes this, then I would propose to create some sort of plugin system.

**Comment by Crecket** [comment]
I've been thinking of adding budgeting features later on and setting saving goals is a pretty great idea 👍 

And I tend to prioritize direct API implementations but useful things like the categories and improved exports are fine to obviously

**Comment by rbarisic** [comment]
Thanks, good to hear :)
I would like to offer some of my time to help working on this project, but I don't like the idea of forking it at this point.

**Comment by Crecket** [comment]
You can now create goals and select which accounts count towards them. Check out the new snapshot build if you want to test it 👍
