### ISSUE TITLE
[Account Overview] Make it more obvious what happens and changes when you click on an Account in Account Overview

### ISSUE THREAD

**Issue by rbarisic** [bunqCommunity/bunqDesktop#380]
**Is your feature request related to a problem? Please describe.**
Currently the account buttons on the account overview work very confusingly. If you you anywhere but the icon, you add or remove the account from the List.

- Arrow means it's in the list
- ( i ) means it's not in the list

This confuses me on a daily basis, also an arrow and an info icon are not opposites, especially since you get to the same page no matter what you click.

**Describe the solution you'd like**
Proposed Solution:

1. There should be a slider on the right side, "on" indicating that the account is in the list, "off" indicating that it's ignored.
2. Clicking on the Account Card should show the information page.

![image](https://user-images.githubusercontent.com/9211959/47077991-8b155a00-d202-11e8-8d02-297dce9fd425.png)

**Comment by Crecket** [comment]
Perhaps we should change it where clicking the main list item send you to the account info page. And the buttons are using a more obvious icon to show they are/aren't used in the account filter. 

The way the account list works right now has stuck around from before the background sync system where you had to be able to quickly click on an account to fetch the events for that account.

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/47314822-164b8100-d643-11e8-9ebd-56414a8a63a1.png)

Selected accounts now have a blue line in front of the selected items. The icon is now always an info icon which sends you to the account page.
