### ISSUE TITLE
Auto correct IBAN number / accept characters

### ISSUE THREAD

**Issue by coinnodenl** [bunqCommunity/bunqDesktop#382]
Got two things that annoy;

- If you dont use capitals in the iban number it will throw an error when you want to pay. Could be easely solved by auto capital the letters.

- You cant use characters in payment description not even if its part of a language like finish.

**Comment by Crecket** [comment]
Do you mean with the second point that special characters aren't allowed?

**Comment by Crecket** [comment]
I fixed issue 1 and improved the iban name field so that one also autocompletes and fills in the IBAN number when possible 👍

**Comment by coinnodenl** [comment]
@crecket, 

Yes

**Comment by Crecket** [comment]
Could you send some example text that doesn't work? I can't reproduce it right now

**Comment by coinnodenl** [comment]
Sorry, its characters as #_ that dont work

**Comment by Crecket** [comment]
I tried those and they seem to work just fine, what is the exact bug? That the description field is red/in the error state?

**Comment by Crecket** [comment]
Nothing in bunqDesktop prevents you from using uncommon characters so if you mean you get an API error screen than there is nothing I can do about it. Closing this for now unless I know how to reproduce a fix-able error for this
