### ISSUE TITLE
Allow users to send a RequestInquiry

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#39]

**Comment by basst85** [comment]
@Crecket What endpoint are you going to use for this? 
https://doc.bunq.com/api/1/call/request-inquiry or https://doc.bunq.com/api/1/call/bunq-me-tab ?  (or both?)

**Comment by Crecket** [comment]
Just the request-inquiry I think for now. I'm planning on adding the basic features like sending payments, requesting payments and accounts transfers first in the next 1-2 weeks
