### ISSUE TITLE
Ability to change the password

### ISSUE THREAD

**Issue by perplexityjeff** [bunqCommunity/bunqDesktop#391]
Hello,

I have been using the app and so far it has been amazing. However it seems currently at least as far as I have looking into the Settings menu that you are unable to change the password required for logging in.

If so it would be a great feature to add. Let me know if I am overlooking something or that this is currently just not available.

**Comment by Crecket** [comment]
One of those things I should've added a long time ago but forgot 😅 thanks for the suggestion

**Comment by Crecket** [comment]
Moving this to the next release

**Comment by Crecket** [comment]
There is now a field on the settings page which will decrypt the current data, switch passwords and then encrypt the data again with the new password. 

It should also update the password for all stored API keys which were encrypted with the same password (So all keys that are clickable in the switch keys menu)
