### ISSUE TITLE
Chrome OS support

### ISSUE THREAD

**Issue by ErnstEeldert** [bunqCommunity/bunqDesktop#392]
Any chance this awesome app could be available on Chrome OS?

**Comment by Crecket** [comment]
This simply isn't possible right now, maybe with the integration of Linux which is apparently happening it might allow for some kind of support in the future. 

I do know you can enable it by using [Crouton](https://github.com/dnschneid/crouton) which requires you to enable developer mode which isn't a great solution for everyone obviously.  So if you really want to run it on ChromeOS you could look into that but there isn't much else I can do sadly
