### ISSUE TITLE
Filtering with a negative filter doesn't filter all the selected items

### ISSUE THREAD

**Issue by Cheaternl** [bunqCommunity/bunqDesktop#397]
When I filter in a specific account, like you see below:

![2018-11-02 23_19_00-bunqdesktop - mastercard info](https://user-images.githubusercontent.com/8473337/47943365-03b03200-def6-11e8-96f4-a41b03cd2bfd.png)

You see there is a scissors icon, which is for my 'kapper' category. Also, I changed the filtering to HIDE these categories instead of showing them via the filter.

However, the list still contains some items which have this 'kapper' category:

![2018-11-02 23_18_15-bunqdesktop - mastercard info](https://user-images.githubusercontent.com/8473337/47943401-30644980-def6-11e8-8e5a-024f76f94efb.png)

Here you see the full specification of the payment:

![2018-11-02 23_16_50-bunqdesktop - mastercard info](https://user-images.githubusercontent.com/8473337/47943413-3b1ede80-def6-11e8-9184-114771b34431.png)

This seems to me incorrect behavior.

**Comment by Crecket** [comment]
Seems to be caused by the negative check causing a match before the categories are checked. Thanks for the report

**Comment by Cheaternl** [comment]
In addition, I can tell that not ALL the items with that category are visible. Most are hidden as they should be.
