### ISSUE TITLE
Scroll to position in list, when going back to overview from payment

### ISSUE THREAD

**Issue by Cheaternl** [bunqCommunity/bunqDesktop#398]
When scrolling down in the list of payments, and clicking on a payment, and clicking the arrow button (back button, top left), the list of payments is reset and on top position again.

For me, this is breaks my flow in looking up payments or changing them, because I have to scroll again to the correct position every time. 

Could you change this behavior? I would suggest overlaying a new screen with the payment details, instead of replacing the contents of the current screen with other info/controls. I'm not sure if it works like this technically, but as a developer, I am implying this.

**Comment by Crecket** [comment]
I implemented a pagination system which should be stored when switching back and forth so I suggest putting that value at 10-20. 

Tracking the scroll position is more difficult to maintain throughout page switches reliably but I'll look leave this open and check how feasible it is to implement this

**Comment by Crecket** [comment]
Yeah using the pagination system is reliable enough imo and tracking the scroll position is a unreliable mess in the current page setup.

Maybe I can add some keybinds for next/previous page on the main dashboard to make things a little quicker? :thinking:

**Comment by Cheaternl** [comment]
Too bad. Maybe consider implementing a screen-over, when clicking a payment (so the overview screen isn't affected)? I think that should be fairly doable, but I haven't viewed any code.

**Comment by Crecket** [comment]
Actually, this might be easier than I thought after looking into this again so I'm adding this to the next release

**Comment by Crecket** [comment]
![restore-scroll-position](https://user-images.githubusercontent.com/7481136/50118985-ae37a680-0251-11e9-8697-d01a9fa52cad.gif)
As soon as you leave a page with the combined list it'll store the current scroll position and then try to restore it once you return

**Comment by OGKevin** [comment]
LMAO those gifs.

**Comment by Cheaternl** [comment]
Haha, nice one! Tnx for implementing!

**Comment by Crecket** [comment]
![338905_278523](https://user-images.githubusercontent.com/7481136/50149632-04413400-02bc-11e9-8d44-fda02d7d1e0f.gif)
