### ISSUE TITLE
Add hotkey for going back to overview

### ISSUE THREAD

**Issue by Cheaternl** [bunqCommunity/bunqDesktop#400]
For me, it feels that the 'payments overview' screen is - **THE** - main screen in the application. All is centralized around this screen. The application even starts with this screen.

So, naturally, I would press escape when in a 'Payment' screen, to go back to the overview. (and i did a couple of times, but that didn't work ofcourse).

As this is a feature request, I have to ask politely, would you consider creating a 'hotkey' (and I think 'escape' is the best key for it) in the application to go back to the overview, when in a Payment screen? Also, this key should hide the filtering menu when it's displayed on the right.

I'm not sure if this feels like natural behavior for other operating systems, because I only use Windows.

**Comment by Cheaternl** [comment]
I do see now, that this hotkey DOES work to hide the menu (after clicking the hamburger icon)

**Comment by Crecket** [comment]
Yeah the escape key is the default to hide a open menu which is by design for the library I use. You can also use the forward/backward buttons on your mouse if you're using one and the Cmd/Ctrl + D key sends you back to the dashboard

**Comment by Crecket** [comment]
Most of the keybinds are just Ctrl/Cmd + first letter of the page right now

**Comment by OGKevin** [comment]
> Most of the keybinds are just Ctrl/Cmd + first letter of the page right now

Which makes sense right ? 😛
