### ISSUE TITLE
Translation error in settings (German)

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#401]
I am using the snap version of bunq desktop and I found an translation error in the settings.
When you activate the automatic refresh in the background you can change the interval for this background sync.

The first option, 1 minute, is called "1 Stunde". But 1 Stunde means 1 hour and not 1 minute. So the correct translation would be 1 Minute.

**Comment by Crecket** [comment]
Should be fixed now, thanks for reporting 👍

**Comment by djohannes** [comment]
> Should be fixed now, thanks for reporting 👍
@Crecket 
Hey, I downloaded the nightly and I see a typo. It's now "1 Minuut" instead of "1 Minute"
