### ISSUE TITLE
What is the point of the password?

### ISSUE THREAD

**Issue by Bodup** [bunqCommunity/bunqDesktop#402]
Not really a bug but more of a logical fallacy, I suppose.
What is the password protecting precisely? The credentials obviously.
But any malicious code that could read the credentials from disk can also wait for the user to type in the password. Perhaps someone who steals the laptop, takes out the hard drive and steals the credentials? He could plant a piece of malware that logs the keys and then sends the credentials.

Anyway point being, in any possible scenario imaginable, the password doesn't actually improve much. So what is it for, really? If the user is worried that malicious code would perform a targeted attack on the desktop app that means he/she doesn't trust the environment that it is running in and therefore the password won't help either.

I'm not sure if it'd be easy, or possible at all. But if the credentials used to authenticate to bunq could be stored in the system keychain, that would offer perhaps some tiny form of protection. 

Edit: I'm not saying storing something used to authenticate to your bank plainly on a desktop system would be a good idea. I'm just saying that encrypting them with something entered on that very same environment doesn't help much. So one should either be up front in saying that running bunq desktop on your typical windows/mac/linux os isn't nearly as secure as it is on your phone, or one should come up with something that actually mitigates the threat.

**Comment by Crecket** [comment]
> Anyway point being, in any possible scenario imaginable, the password doesn't actually improve much. 

If someone gets access to the device then the data won't be available by starting bunqDesktop, copying the app files or stealing the hard drive. Those are all the most likely situations I can think of besides having an active virus on the system.

> If the user is worried that malicious code would perform a targeted attack on the desktop app that means he/she doesn't trust the environment that it is running in and therefore the password won't help either.

Obviously the password isn't going to protect you if the device has a keylogger installed, I don't really see how that makes the password useless. And if a user is worried about a situation like that than that user shouldn't even be using a desktop app or website to access their banking data.

The password isn't some bulletproof system against that, and it isn't meant to be.

**Comment by Bodup** [comment]
> And if a user is worried about a situation like that than that user shouldn't even be using a desktop app or website to access their banking data.

That is basically what I meant. 

> If someone gets access to the device then the data won't be available by starting bunqDesktop, copying the app files or stealing the hard drive.

Not immediately, indeed. You would either bruteforce it or pop a keylogger on the system. 
if all the password does is protect against very low tech attacks, it's not _completely_ useless I'll give you that. But it just seems strange to me to go through the effort of typing it every time if it can be so easily circumvented, mostly for fuzzy feelings of security. 

Just a thought though. I'll close the issue. Maybe consider making the password optional? I'd personally run it inside a [Qubes-OS VM](https://www.qubes-os.org/) anyway.

**Comment by Crecket** [comment]
> Maybe consider making the password optional?

You can click "Skip" if you wish to use no password btw. It'll still use a default password in the background so no data is stored in plain text

**Comment by Bodup** [comment]
Ah, I hadn't noticed. Thanks!
> It'll still use a default password in the background so no data is stored in plain text

Great, at least now someone can't get my credentials if they get the ciphertext with the default password
