### ISSUE TITLE
Scheduled payments show "insufficient funds" warning

### ISSUE THREAD

**Issue by tobyurff** [bunqCommunity/bunqDesktop#403]
### Reproduce

- Create a new payment.
- Enter an amount that is higher than current funds on the account.
- Try scheduling the payment for in a month's time.

![Screencast of issue](http://secret.tobi.link/f871c388b351/Screen%20Recording%202018-11-06%20at%2008.07%20PM.gif)

### Expected

The payment should be possible since the funds might be sufficient in the future – or will be listed as failed as a failed transaction.

### Actual

The insufficient funds warning is shown and the payment isn't possible (button inactive).

**Comment by Crecket** [comment]
Thanks for fixing this, I'll check the PR when I get back from the bunq update
