### ISSUE TITLE
Detect Windows 10 dark mode and switch dark and light theme correctly

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#409]
It's the same like this: https://github.com/bunqCommunity/bunqDesktop/issues/384 - only for windows 10, there is also a dark and light theme.
I am not a developer and I don't know if normal win32 apps can detect it with some sort of API, but there is a reg key:
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme - maybe the app could read it.

**Comment by djohannes** [comment]
I searched a bit and I don't think this will work with getColor. Reading the reg key is as it seams the only way.

**Comment by Crecket** [comment]
Checking the registry with Electron is tricky since it requires native modules which might cause issues on other platforms which I try to avoid. 

Unless Electron adds an API to check for a real "Dark mode" like is possible with MacOS I won't be implementing this.
