### ISSUE TITLE
Improve switch accounts

### ISSUE THREAD

**Issue by Wouter0100** [bunqCommunity/bunqDesktop#411]
Currently - the ability to switch between accounts is quite confusing/long. I have 3 accounts to work with, at first I had them setup with the same device name (as I thought this was required, because I was on the same device):
![image](https://user-images.githubusercontent.com/864520/48282052-e67ce580-e458-11e8-8fcf-8387ac682148.png)

But now I've solved that by re-adding them with a different name. I think, in the end, the user doesn't really care which API key he's using - just which account is loaded. Some small UX improvement which improves the usability a lot for users with more accounts.

Regardless, switching between accounts also involves some clicks that I believe could be optimised:
1. Click "Switch API keys" in the right upper corner.
2. Sign in (I have all with the same password).
3. Click "Switch keys" in the right upper corner.
4. Click the API key I'd like to start using.
5. A (long) loading screen which isn't clear what it does ("You're logged in!").

I guess the "ideal" scenario would be that it detects that I have multiple API keys with the same password, and allows me to quickly switch between them. For example, my first instinct was to click on the avatar near "Welcome {name}". Another possibility would be just like how Android does it - in the menu bar. Where the bunqDesktop with the version is placed, place the currently active user with the ability to quickly switch between available accounts.

Tasks
 - [x] Allow users to edit the device names for stored keys
 - [x] Make it easier to switch keys (Directly from a logged in user?)

**Comment by Crecket** [comment]
![ezgif-1-e071203ee67a](https://user-images.githubusercontent.com/7481136/48305378-ab96b280-e529-11e8-9af8-c7c45982116c.gif)

Still needs some work but "it works" 😋 Basically it logs you out and starts a login process automatically

**Comment by Wouter0100** [comment]
Awesome work! 😎 Can't wait to use it.
