### ISSUE TITLE
Payments not shown

### ISSUE THREAD

**Issue by stefan52a** [bunqCommunity/bunqDesktop#416]
This happens to me I guess 50% of the time.
Sandbox version on Ubuntu 18.04 and bunqDesktop 0.9.1
A payment exists, as can be shown in the debug window:
![screenshot from 2018-11-12 23-56-34](https://user-images.githubusercontent.com/39596377/48380244-3c5ec100-e6d7-11e8-8ed4-29c1709bf510.png)
However it does not ever display in the UI, while running:
![screenshot from 2018-11-12 23-57-45](https://user-images.githubusercontent.com/39596377/48380260-47195600-e6d7-11e8-94a0-56db9410a6cc.png)
After stopping and restarting the bunqdesktop app, it does however show:
![screenshot from 2018-11-12 23-58-33](https://user-images.githubusercontent.com/39596377/48380274-57313580-e6d7-11e8-83ed-923584d51a37.png)

**Comment by Crecket** [comment]
Which type does that payment have?

**Comment by stefan52a** [comment]
Type is BUNQ i Guess
![screenshot from 2018-11-13 00-42-27](https://user-images.githubusercontent.com/39596377/48381614-06bcd680-e6dd-11e8-8822-b0e77c988934.png)

**Comment by stefan52a** [comment]
BTW I use a snapshot release:
![screenshot from 2018-11-13 00-44-27](https://user-images.githubusercontent.com/39596377/48381670-526f8000-e6dd-11e8-8cd3-bc8adec8d5f7.png)

**Comment by OGKevin** [comment]
@stefan52a did you use the snapshot or `0.9.1`? As in the OP you say `0.9.1` and no snapshot 🤔 makes debugging easier if the version is clear.

**Comment by Crecket** [comment]
It looks like it might be a loading issues since the events count switches between 120 and 79. Or a old value which was causing issues when switching from the current release version (0.9.1) to the snapshot build.

I'll leave this open until the events endpoint is implemented which will significantly simplify the data handling process and will likely fix this issue.

**Comment by OGKevin** [comment]
> I'll leave this open until the events endpoint is implemented

![](https://media.giphy.com/media/u5eXlkXWkrITm/giphy.gif)

**Comment by stefan52a** [comment]
BTW I do not experience the behaviour on a Windows machine; but do on Ubuntu 18.04.

**Comment by stefan52a** [comment]
It donot have the problem in windows 10. Only in Ubuntu 18.04
