### ISSUE TITLE
Register Callback URL 

### ISSUE THREAD

**Issue by hendrer** [bunqCommunity/bunqDesktop#420]
**Is your feature request related to a problem? Please describe.**
I'm using Azure to integrate bunq with YNAB and it would be great if you would introduce a feature to register a callback URL. 

**Describe the solution you'd like**
Within the UI, you allow registering a callback URL with filters. 

**Additional context**
Essentially a UI implementation of the Callbacks API.

**Comment by OGKevin** [comment]
but what I don't understand is, _why_ should it be in bunq desktop? And not in your own "integration" what benefit would it bring to be able to register webhooks in  bunqDesktop 🤔

**Comment by hendrer** [comment]
I saw this question coming 😊 The real benefit is that I don’t have to deal with all the overhead of installing / authorizing / session management when you’ve have all the foundational work completed already. 

Sent from Mail for Windows 10

**Comment by OGKevin** [comment]
> Unless I'm mistaken the callbacks are shown for all sessions so to speak, so it would also give users more insight into which callbacks are currently set for their account.
> 
> And for developers it'd be a pretty useful feature aswell obviously

Alright, this is indeed a valid point.
