### ISSUE TITLE
ChromeOS Support

### ISSUE THREAD

**Issue by SamAriafar** [bunqCommunity/bunqDesktop#461]
That would be great if you make a release for ChromeOS as well. Although ChromeOS supports a wide range of Android Apps, but unfortunately Bunq app itself cannot be installed on it due to lack of support. Perhaps you can make your desktop edition ready for either of those.

**Comment by Crecket** [comment]
It is simply not possible to release for ChromeOS using Electron and I don't plan on creating a secondary application just for ChromOS.

**Comment by SamAriafar** [comment]
@Crecket all Android and Debian Core Linux apps can technically run on ChromeOS also, however Google Play doesn't let your Android app to be downloaded and installed on this device for instance.
