### ISSUE TITLE
Transaction overview

### ISSUE THREAD

**Issue by jordywichgers** [bunqCommunity/bunqDesktop#463]
**Describe the requested feature:**
 
By viewing a transaction I would love to add a category as well. The rules for categories are not always working. So it would be great if we can multi-select the transactions and assign them to a category. 

**Additional context:**
In this case I would love to add a category but I don't have that option and don't get the reason why it is not possible.

<img width="832" alt="screenshot 2018-12-29 at 13 24 33" src="https://user-images.githubusercontent.com/38910175/50538293-69731000-0b6d-11e9-9834-a31e8420b2cc.png">

**Comment by Crecket** [comment]
As discussed in Telegram you can set a category through the button in the bottom right 👍
