### ISSUE TITLE
Arch user repository link in README

### ISSUE THREAD

**Issue by Archcry** [bunqCommunity/bunqDesktop#467]
**Describe the requested feature:**
 
I was browsing through this repository and I noticed there are several ways for distributions to install Bunq desktop (snap for Ubuntu, brew for Apple and Chocolatey). So at first I just downloaded the binary and launched it (which worked fine). But then I wondered if I could make an AUR package for it. Turns out there is an AUR package there already. It would be nice to add it to the README. Though the other repositories also list the command to install, this is a little more complicated for the AUR because there are several AUR helpers that are being used in the Arch community. I would use `trizen -S bunq-desktop-bin` for example.

**Additional context:**
Link to AUR package: https://aur.archlinux.org/packages/bunq-desktop-bin/
Link to available AUR helpers: https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by Crecket** [comment]
Completely forgot to add it to the readme. We did list it on the bunqdesk.top site so I'll add it here aswell.

The one that was recommended to me was using `$AURHELPER -S bunq-desktop-bin` which I assume is a standard reference to a AUR helper?

**Comment by Archcry** [comment]
Well, on Arch `$AURHELPER` doesn't really reference anything, it's more of a way to make clear that users should use some aur helper I guess. But I think people will realize what they have to type when you specify it like that.

**Comment by Crecket** [comment]
Done 👍
