### ISSUE TITLE
Payment request keeps in pending state

### ISSUE THREAD

**Issue by stefan52a** [bunqCommunity/bunqDesktop#470]
Sandbox.
Happens every time I am requesting a payment from e.g. sugardaddy@bunq.com
See picture of part of Dashboard picture
![screenshot from 2019-01-14 01-58-41](https://user-images.githubusercontent.com/39596377/51093130-5af93b00-17a0-11e9-8105-80baeb9b5ff1.png)
Ubuntu 18.04 bunqdesktop 0.9.5

Also cannot pay. See other enclosed picture.
![image](https://user-images.githubusercontent.com/39596377/51093327-b4626980-17a2-11e9-9981-742745d790cc.png)

**Comment by Crecket** [comment]
Caused by the sandbox environment, no idea when it'll be fixed.

**Comment by Crecket** [comment]
Fyi, sending payments should be fixed now. A bunq employee is still checking the bug with the requests
