### ISSUE TITLE
Error in app.asar file thrown in the "about" pane

### ISSUE THREAD

**Issue by taue2512** [bunqCommunity/bunqDesktop#477]
An error is thrown because a parameter was not found in the config file in v0.9.5 of the app.

![image](https://user-images.githubusercontent.com/13081752/52789813-3de8ae00-3065-11e9-89f3-5ec7cb1b201c.png)

**Comment by Crecket** [comment]
Thanks for reporting. This has been fixed in the development version

**Comment by taue2512** [comment]
I’ve updated some typos and translation errors in the German language file…

—
Ralf-Martin Tauer
Phone +49 170 7968089

**Comment by Crecket** [comment]
@taue2512 you can add translations more easily on our Crowdin system found here: https://crowdin.com/translate/bunqdesktop/24/en-de
