### ISSUE TITLE
Circle around additional accounts is misaligned in the GUI when amounts are shown vs. hidden in app settings

### ISSUE THREAD

**Issue by taue2512** [bunqCommunity/bunqDesktop#478]
![image](https://user-images.githubusercontent.com/13081752/52790043-cebf8980-3065-11e9-9890-194be196e188.png)

![image](https://user-images.githubusercontent.com/13081752/52790052-d5e69780-3065-11e9-9a26-a17bde2f4beb.png)

**Comment by Crecket** [comment]
🤦‍♂️ Thanks for reporting

**Comment by Crecket** [comment]
Just for documentations sake, this is actually caused by the multi lines from the savings goal not fitting properly.
