### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#484]
Windows 10, using bunqDesktop 0.9.5. Clicking on "Dashboard" gave the error "cannot read property 'file' of undefined", see screen shot below.

[Error screen shot](https://user-images.githubusercontent.com/23123995/53319195-21a10880-38d2-11e9-845f-df5aa92664e1.png)

**Comment by Crecket** [comment]
Thanks for reporting, this has been fixed on the development branch
