### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#486]
### Bug report

Hi,

since the new update my bunqDesktop is basically not working anymore, also after a re-installation. The first time it shows my accounts, but it doesn't load the payments.. then I get the:
"TypeError: Cannot read property 'status' of undefined" - error.

**Comment by djohannes** [comment]
.. If you need more information about this I would be happy to provide them :)

**Comment by Crecket** [comment]
This is likely caused by a breaking API change on bunq's end. One of the connect models got a name change so it should be an easy fix :+1:

**Comment by Mauricevb** [comment]
Do you think it's possible to release a hotfix with these changes?

**Comment by Crecket** [comment]
Later today probably

**Comment by Crecket** [comment]
Fixed by bunq 👍  I'll release a new version with some of the new changes later aswell
