### ISSUE TITLE
Button texts untranslatable

### ISSUE THREAD

**Issue by rvdsteege** [bunqCommunity/bunqDesktop#493]
Some buttons are untranslated and are not made in a way that they can be translated.

![schermafbeelding 2019-03-02 om 12 08 30](https://user-images.githubusercontent.com/10371164/53681050-f5c3bf80-3ce3-11e9-82eb-524eaa483082.png)

**Comment by Crecket** [comment]
I'll wrap these in the translation handlers in a bit, thanks for spotting 👍

**Comment by Crecket** [comment]
Should be visible in crowdin now 👍

**Comment by rvdsteege** [comment]
Thanks. However, besides the settings, there were some more missing translatable buttons. PR #494 should fix them all.
