### ISSUE TITLE
Not all Virtual Cards visible

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#497]
The new update is amazing again, but I have some problems with the new virtual cards support:
1. I only see one of it and when I change the account of it, it doesn't change the account of any of my virtual cards.
2. And it has a name I'm not even using anymore, it's the name of my first virtual card that I removed. Is this maybe a issue at bunq itself?

**Comment by Crecket** [comment]
This is an issue with the API. I'll leave this up for people to see though.

Basically the virtual card is 1 card but with multiple numbers and names. So the public endpoint is only showing the first virtual card at the moment.

**Comment by basst85** [comment]
The virtual cards (online cards) are now available via the API. They are in the "primary_account_numbers_virtual" object of the CardDebit response (card endpoint).  When type=MASTERCARD_VIRTUAL

**Comment by Crecket** [comment]
Fixed in 0d1e892000523b1affdffd164c0bc9efaa88d50f

![image](https://user-images.githubusercontent.com/7481136/56862321-00c86280-69aa-11e9-8fa2-51f43fdd38ee.png)
