### ISSUE TITLE
Save API-key and session data encrypted in local storage

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#5]
I think it's more secure to make the API-key invisible (in login screen) and save it encrypted in local storage.

Check my encrypt and decrypt functions:
https://github.com/basst85/bunqClient/blob/master/electron-vue/src/methods/index.js

When loggin in the user need to enter the correct password to decrypt. 👍

**Comment by ntimo** [comment]
I would also love this feature, just let the user set a password that will be used to encrypt the api key. Or maybe store it in the macOS keychain.

**Comment by Knight1** [comment]
Or just a simple PIN

**Comment by Crecket** [comment]
The main issue with using a pin is that if someone does get access to your PC they only need to bruteforce 4^10 combinations. So even if one attempt were to take a minute they'd still be able to get the API key and other data within ~7days.  

Personally I think a 7+ alphanumeric password would be required if we want to store the data securely.  I thought about adding the option for both but we'd only be giving the user a false sense of security by allowing pin encryption without some kind of hardware key

**Comment by ntimo** [comment]
@Crecket I think a alphanumeric password with 7+ caracters would be the best solution.

**Comment by Crecket** [comment]
I setup basic encryption for the API key on the BunqDesktop side here 9f85da4. The next step will be adding the encryption key to the BunqJSClient setupso the actual session information is secure aswell.

**Comment by Crecket** [comment]
When no API key is stored yet this is shown:
![image](https://user-images.githubusercontent.com/7481136/31855224-207ede36-b6a7-11e7-9ccb-eec8513c93e4.png)
If an API key is already set the user can reset the stored data and start over
![image](https://user-images.githubusercontent.com/7481136/31855228-3f20b1b6-b6a7-11e7-98c8-7a6ada23285a.png)

**Comment by DennisSnijder** [comment]
@Crecket Awesome progress man!

**Comment by ntimo** [comment]
@Crecket this looks awesome! Can't wait for it :) What encryption do you use?

**Comment by Crecket** [comment]
AES-CBC-128 for encryption both in BunqDesktop  and the BunqJSClient and PKCS#5 to turn the password into a compatible key
