### ISSUE TITLE
Update userinfo fails when field contain diacritics like é

### ISSUE THREAD

**Issue by pl0ink** [bunqCommunity/bunqDesktop#504]
When attempting to update my address information in the bunqDesktop using the Update Userinfo screen I constantly experience the error below:
 

"Something went wrong
We failed to update your user information:
The request signature is invalid.
Response-Id: 9fb04abb-ad4b-4f51-a2ba-07cc5f8d6749" 

I could change my address without any issues in the Bunq App.

After troubleshooting I discovered that the cause of this error was the use of a diacritic character in the nick name field.  (my name is René)

But the same error occurs when using such a character in other fields like "Street".

Tested with version 0.9.6 on Windows 10 and MacOS.  

To replicate the error:

Open Update Userinfo screen by clicking on profile picture.
Change field "public nick name" to: René
Click Update.

**Comment by Crecket** [comment]
Hm someone else also reported this, I'm guessing the special characters aren't encoded correctly. Thanks for reporting this

**Comment by Crecket** [comment]
While fixing file uploads which required `raw` encoding we broke support for certain characters. Should be fixed now, thanks for reporting
