### ISSUE TITLE
Can't leave contacts screen

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#506]
Windows 10, bunqDesktop 0.9.6.

When you make a payment you can click on a button "Contacts". You then get an overview of your contacts. I have none (I don't really want to add any either). So how do I get back to my payment? As far as I can tell there is no way to return to the previous screen. Of course I can select "Pay" from the hamburger menu again, but then all the fields have to be entered again.

![Contacts](https://user-images.githubusercontent.com/23123995/55141401-a6ce4600-513a-11e9-9f78-30b6eee1ad6a.png)

**Comment by Crecket** [comment]
Ah thanks, can't believe no one has noticed this until now haha. I'll add the back and home buttons like the other pages have.
