### ISSUE TITLE
Back Button Missing

### ISSUE THREAD

**Issue by djohannes** [bunqCommunity/bunqDesktop#508]
Hey,

at some places the back button is missing in my opinion:
1. You click on forward or request at a payment and you want to go back to the payment, there is no back button to do so.
2. You start a new payment and you click on "contacts" to import your Google Contacts or other contacts, no back button to go back to the payment process

**Comment by Crecket** [comment]
For the record, you can use the backward/forward buttons on your mouse. And there is already an issue for the Contacts page specifically so I'll track the missing back buttons there 

Related to #506
