### ISSUE TITLE
IBAN copied to clipboard is black on very dark grey

### ISSUE THREAD

**Issue by JeroenEeuwes** [bunqCommunity/bunqDesktop#510]
bunqDesktop 0.9.6, Windows 10

When you copy an IBAN and paste it into Word it shows up as black text on a very dark grey background. Is it possible to copy the IBAN without the unreadable formatting?
![Word](https://user-images.githubusercontent.com/23123995/55664967-74f26900-5837-11e9-8e5b-0fd0cb207203.png)

**Comment by Crecket** [comment]
Ah never realized they also copied the background content, thanks for the report
