### ISSUE TITLE
Something went wrong! in Cards

### ISSUE THREAD

**Issue by CoreISP** [bunqCommunity/bunqDesktop#518]
Hi,

With the latest version (bD 0.9.7, macOS Mojave 10.14.4), the "Cards" screen crashes as soon as you reach the Online Cards card in the list. If I skip it by clicking the card below it, it can jump to that OK. As soon as you click the Online Card or scroll up/down to it, it shows:

**Something went wrong!**
_TypeError: Cannot read property 'filter' of undefined_
    at n.value (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/cards.bundle.js:32:7634)
    at Aa (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:63088)
    at Oa (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:62883)
    at Ra (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:66730)
    at zi (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:90799)
    at Ki (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:91183)
    at As (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:98070)
    at xs (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:97450)
    at Es (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:96471)
    at Qi (file:///Applications/bunqDesktop.app/Contents/Resources/app.asar/app/react/vendor.bundle.js:3049:95345)

It can be resolved for now by downgrading to 0.9.6 by the looks of it.
Incidentally, the Dashboard section seems to hang a lot in this version. It won't respond to any input at all right after finishing background sync. This may hang for up to 5 - 7 seconds. Not a major concern, just an FYI.

Further environmentals that may be of use:
- 9 Online Cards (5 active)
- Different countries per card may occur 
- Cards may be active in Apple Pay
- No custom order, order is default; shows up as third in the list for me
- There are special characters in one of my card names, including a / and a -
- In account names associated with the virtual card(s), special characters can show up including /, - and &. 
- If you're unlucky and bunqDesktop remembers where you were in the list, it will be impossible to open the Cards tab again until you downgrade.
- Logs simply reveal the same output

Thanks :)

**Comment by Crecket** [comment]
It looks like a property called `primary_account_numbers_virtual` isn't available when it should be. 

Could you open the cards page, then go to the settings page, click the "Debug application" button and then check the `cards` item in the list there? You should look for a card with type `MASTERCARD_VIRTUAL` and it should have the `primary_account_numbers_virtual` property both marked in red here:

![Screenshot from 2019-05-02 10-06-16](https://user-images.githubusercontent.com/7481136/57063152-9291e180-6cc2-11e9-9515-b0d240f187a4.png)

**Comment by CoreISP** [comment]
@Crecket There is nothing beyond "pin_code_assignment".
Compared to your screenshot, the following is missing:
- country
- country_permission
- label_monetary_account_ordered
- label_monetary_account_current
- primary_account_number_four_digit
- primary_account_numbers_virtual

This is missing on all cards.
I just checked, and this information does not show up for any card whilst using oAuth. (The rest loads fine though) It does show up when using API.

**Comment by Crecket** [comment]
Ah I'm guessing this is related to using OAuth where certain card details aren't available. Stupid mistake on my part, thanks for checking. 

It should be fixed now so you can grab the nightly build tomorrow.

**Comment by CoreISP** [comment]
Thanks! :)

**Comment by Crecket** [comment]
Yeah so using OAuth means it isn't possible to view the different virtual cards at all instead of the private details just being hidden like what happens with the other cards :thinking:

**Comment by CoreISP** [comment]
@Crecket Indeed, judging by the debug output: that isn't possible.
Incidentally, when you select "Display inactive cards", this doesn't show deactivated online cards either whilst I do see them in the debug output. (At least, I see them linked to monetary accounts)

By the way, I see this i (information) button behind each virtual card which lists the transactions done with that online card. How does one do that with the other cards? That's rather handy! :)

**Comment by Crecket** [comment]
That button simply goes to the monetary account that is linked to that virtual mastercard at the moment similar to clicking on any of the accounts in the accounts list

**Comment by CoreISP** [comment]
@Crecket Lol, do'h. I clicked it on a card that has its own account specifically for online payments. Didn't notice it just jumped to the account. :P Thanks ;)
