### ISSUE TITLE
Account object doesn't contain a 'balance' key causing a fatal error

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#53]
It seems some accounts do not contain a 'balance' which causes the following bug when trying to access the account.balance.value
`Cannot read property 'value' of null`

**Comment by DennisSnijder** [comment]
Perhaps ask Bunq support about this scenario?

**Comment by Crecket** [comment]
I added a default value on the locations where we access the account's balance and logging the account info to the log file in the `balance-error` branch
```JS
const formattedBalance = formatMoney(
    account.balance ? account.balance.value : 0
);

// debug the account result
if(!account.balance){
    Logger.error("Account balance is missing");
    Logger.error(JSON.stringify(account));
}
```

**Comment by Crecket** [comment]
Fixed 👌
