### ISSUE TITLE
Downloading the installers doesnt work

### ISSUE THREAD

**Issue by matrover** [bunqCommunity/bunqDesktop#530]
Also not via homebrew 

error: https://github-production-release-asset-2e65be.s3.amazonaws.com/107038254/67348980-7e5f-11e9-8fba-950235087778?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKXXXXXXXXXXXXXA%2F20190613%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190613T140649Z&X-Amz-Expires=300&X-Amz-Signature=a58c69XXXXXXXXXXXXXXXddd119c2991ff5cc4b1af35ef45536b4&X-Amz-SignedHeaders=host&actor_id=184XXXX57&response-content-disposition=attachment%3B%20filename%3DbunqDesktop-0.9.8.exe&response-content-type=application%2Foctet-stream 

unreachable

**Comment by Crecket** [comment]
Uh that is an issue with Github, all homebrew does in the background is download the correct file from github.

Try again in a couple of hours, it might be a connection/server issue

**Comment by matrover** [comment]
Works again, thnx
