### ISSUE TITLE
Easier switch to multiple accounts?

### ISSUE THREAD

**Issue by royberris** [bunqCommunity/bunqDesktop#534]
[//]:# ( Please note: )
[//]:# ( These steps are guidelines and not required. Going through them might prevent duplicate or outdated issues. )
[//]:# ( Feel free to add translations yourself! Contact us if you need help getting started. )

**Describe the requested feature:**
So I looked thru this github page and I understood that it is possible to have multiple account based on the API keys? Which I couldn't get to work btw. But is there a way we would be able to just press a button and all my logged in accounts show up (like the app).

**Additional context:**

I would like to help you guys out if it is too much work.

Looking at the application all data is loaded thru the selected API key right? So I would say that if it was build with this in mind that it is really 90% UI? Correct me if I'm wrong. I am a android developer so I know how annoying it is if someone says that "But it is not that hard right?". While is basically messes up the whole core system.

**Comment by Crecket** [comment]
https://wiki.bunqdesk.top/setup/setup-multiple-accounts/ 

Basically you can log out and log in to a different account. From that point on you should be able to switch instantly from the desktop and from the login screen itself.
