### ISSUE TITLE
Error "Failed to load the share invite inquiries/responses: Route not found."

### ISSUE THREAD

**Issue by Gianorange** [bunqCommunity/bunqDesktop#536]
I get these errors every time I open my _Dashbord_ or go to the tabs _bunq.me Requests_ and _Stats_. 

> We failed to load the share invite inquiries for this monetary account:
> 
> Route not found.
> 
> Response-Id: _______________________________

> We failed to load the share invite responses for this account:
> 
> Route not found.
> 
> Response-Id: _______________________________

Tried both on version 0.9.7 and 0.9.8, on two different machines (a Windows 10 Home laptop and Windows 10 Pro desktop) and on two different connections (office wifi and android mobile hotspot from my personal phone).
Sometimes the error is about share invite inquires, sometimes responses, sometimes it looks like it's both (I can see the error changing after a split second it appeared).

Also, on 0.9.7 I get a "We failed to load the cars overview" error when I try to go the card tab, but I'm not sure if it is relevant since it doesn't happen in 0.9.8.

Screenshots of the errors:
![bunqerror](https://user-images.githubusercontent.com/56921599/67393463-b4e62700-f5a2-11e9-82cc-4fa17115e4a3.png)
![bunqerror2](https://user-images.githubusercontent.com/56921599/67393464-b57ebd80-f5a2-11e9-9f2e-cde1472f6f83.png)
![bunqerror3](https://user-images.githubusercontent.com/56921599/67393465-b57ebd80-f5a2-11e9-9c94-15325b36d1e3.png)

**Comment by arthursoares** [comment]
I'm getting the same error.

**Comment by Crecket** [comment]
Caused by breaking changes in the bunq API, I'm not sure when I'll be able to fix it as I'm busy with other things

**Comment by Sm0ke0ut** [comment]
I'm having the same issues. Is there a way to suppress the error until a fix is available?

**Comment by mlgrm** [comment]
bump.

**Comment by MoweME** [comment]
same problem here.

**Comment by LisaHolenstein** [comment]
Same problem in Version 0.9.8

**Comment by heijligers** [comment]
bump
