### ISSUE TITLE
Export bank statement

### ISSUE THREAD

**Issue by mrvanosch** [BunqCommunity/BunqDesktop#54]
Maybe you can download an idea for Export also for your account statements

**Comment by DennisSnijder** [comment]
We already have an issue for exports #20 

Or is this something else?
Closing the issue for now..

**Comment by mrvanosch** [comment]
Yes

Verzonden vanuit Mail voor Windows 10

Van: Dennis Snijder
Verzonden: vrijdag 3 november 2017 17:19
Aan: BunqCommunity/BunqDesktop
CC: mrvanosch; Author
Onderwerp: Re: [BunqCommunity/BunqDesktop] Export bank statement (#54)

We already have an issue for exports #20
Or is this something else?
Closing the issue for now..
