### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by TwodoHD** [bunqCommunity/bunqDesktop#546]
I always explained the error here: https://together.bunq.com/d/5763-bunqdesktop-the-unofficial-free-and-open-source-desktop-application-for-bunq/175 "Something went wrong".

**Comment by firstred** [comment]
Can you explain what went wrong? Is it the error from #536?

**Comment by Crecket** [comment]
Likely related so I'm closing this for now. Create a new issue if it's unrelated to 536 linked above
