### ISSUE TITLE
mobiele app Android apk-file op website graag (en in /e/ app store)!

### ISSUE THREAD

**Issue by Rik44444** [bunqCommunity/bunqDesktop#579]
Beste BUNQ,

sorry, duidelijk de verkeerde plek om dit te posten, maar er is (nog...?) geen Github voor de mobiele app. 

De reden voor mijn post: ik heb een Android telefoon, maar ik gebruik een [nieuw soort Android, /e/](https://e.foundation), die probeert een privacy-veiligere ervaring neer te zetten dan Google doet. Dit kan, want Android is open-source, net als jullie desktop app:). Echter, ik kom er net achter dat de BUNQ app niet verkrijgbaar is in de /e/ app store. 2 verzoeken:

1. kunnen jullie de app beschikbaar maken in de /e/ app store? (ik kan jullie in contact brengen met de juiste mensen). De /e/ telefoons zijn overigens niet rooted, dus er is geen extra risico.
2. kunnen jullie de Android app, net als de desktop apps, beschikbaar maken op jullie website? Dit is eigenlijk de beste methode: het is A) het veiligst, B) jullie hoeven niet met meerdere app stores te werken (=goedkoper), en C) je zit niet vast aan het Google / Apple duopolie (= goedkoper en dan kunnen mensen zoals ik die daarvan proberen weg te komen de app ook downloaden). Dit zou niet veel werk moeten zijn: jullie maken de apk-file ook beschikbaar aan de Play Store van Google, het is alleen een kwestie van em online zetten.

Ik wil graag weer bunqen, dus ik hoop dat (een van) deze 2 punten kunnen!

Rik

PS /e/ heeft een vrij actieve op privacy gerichte community, en banken zijn traditioneel langzaam in het aanpassen aan dit soort ontwikkelingen. Veel denken dat dit soort Androids onveilig zijn, terwijl het omgekeerde waar is (elke Google telefoon geeft 360x per dag de lokatie van de gebruiker door aan de Google servers in Amerika!). Als jullie hier pro-actief in zijn en de apk-file van de app op jullie website plaatsen, weet ik zeker dat het binnen deze community voor positieve PR zal zorgen en daarmee wellicht nieuwe klanten!

**Comment by Crecket** [comment]
Dit is een community project en niet een officiele bunq app. Daarnaast is bunqDesktop is een desktop project en heeft niks te maken met eventuele mobiele apps.
