### ISSUE TITLE
Lock the application after X minutes of inactivity or if the device goes inactive

### ISSUE THREAD

**Issue by Crecket** [BunqCommunity/BunqDesktop#64]

**Comment by DennisSnijder** [comment]
I think this should be an option.
What do you think?

**Comment by Crecket** [comment]
Yeah definitely make it optional, I'll probably work on this along with the option to force draft-payments.

**Comment by Crecket** [comment]
![image](https://user-images.githubusercontent.com/7481136/32600002-7148a84c-c53e-11e7-97d8-8cd73d5a93d7.png)
Using the electron power-monitor module we can easily detect sleep/power-on events
