### ISSUE TITLE
Archived Accounts are included in Account Number Count

### ISSUE THREAD

**Issue by janxb** [BunqCommunity/BunqDesktop#68]
App Version: 0.6.2
OS Version: Windows 10 x64

I have three active bunq accounts and two archived ones. In the BunqDesktop app, the text at the top says "bunq accounts - 5". It seems like the number shown there also includes archived accounts, not only active ones.

Either the number should be calculated excluding archived accounts, or there should be the possibility to view archived accounts.

![bunqdesktop-archivedaccounts](https://user-images.githubusercontent.com/1172106/32785017-ba53102a-c950-11e7-8919-80c4510a3a25.png)

**Comment by Crecket** [comment]
Thanks for the bug report. I fixed it and this will be added in 0.7.0
