### ISSUE TITLE
IBAN with spaces gives non-formatted HTML error message

### ISSUE THREAD

**Issue by janxb** [BunqCommunity/BunqDesktop#69]
BunqDesktop 0.6.2 on Windows 10 x64

When creating a new payment to an IBAN, i can't use spaces in the address. I think they should be automatically filtered out.

After confirming, the error message has an HTML code for a line break in it, but it doesn't work. The HTML code is displayed in cleartext instead.

![bunqdesktop-errormessage-linebreak](https://user-images.githubusercontent.com/1172106/32829168-8deedc70-c9f1-11e7-929e-3f2495614f18.png)

**Comment by Crecket** [comment]
The second bug with the <br/> tag has already been fixed in the current version. I'll make sure to strip all spaces from the IBAN number before verifying the results 👍
