### ISSUE TITLE
Refused MasterCard payments displayed as normal payments

### ISSUE THREAD

**Issue by basst85** [BunqCommunity/BunqDesktop#77]
Refused (online) MasterCard payments are displayed as normal (accepted)  payments.

Attribute values of a blocked payment: 

authorisation_status=BLOCKED
authorisation_type=NORMAL_AUTHORISATION

And you have a property "decision", for example "INSUFFICIENT_BALANCE"

**Comment by basst85** [comment]
You have also the property "decision_description" with a more "human readable" textual explanation of why it was denied.

Possible authorisation statusses:
CLEARING_REFUND
PRE_AUTHORISED
PRE_AUTHORISATION_FINALISED
PRE_AUTHORISATION_EXPIRED
REVERSED
REVERSED_PARTIAL
ACQUIRER_AUTHORISED
AUTHORISED
AUTHORISED_PARTIAL
BLOCKED
IGNORED
NOT_PERFORMED
PENDING
STAND_IN_AUTHORISED
UNAUTHORISED_CLEARING

Authorisation types:
CLEARING_REFUND
PRE_AUTHORISATION
ACCOUNT_STATUS
BALANCE_INQUIRY
ATC_UPDATE
FINAL_AUTHORISATION
NORMAL_AUTHORISATION
STAND_IN_ADVICE
TOKEN
UNAUTHORISED_CLEARING
UNMATCHED_REVERSAL

**Comment by Crecket** [comment]
This has been implemented in 0.7.4 but due to all the different types and statuses we'll slowly implement more detailed and user-friendly descriptions to the card payments
