### ISSUE TITLE
Direct Debit is duplicated in Transaction Overview

### ISSUE THREAD

**Issue by janxb** [BunqCommunity/BunqDesktop#81]
Windows 10 x64 with BunqDesktop 0.7.3

A SEPA direct debit is showing up multiple times on my transaction overview.

![bunqdesktop-duplicated-directdebit](https://user-images.githubusercontent.com/1172106/33175177-16ecc720-d05b-11e7-8728-f487127576b7.png)

**Comment by Crecket** [comment]
This is caused by the actual request still being shown as completed. We have fixed this in the next version
