### ISSUE TITLE
Transaction is grouped by the wrong Date in Overview

### ISSUE THREAD

**Issue by janxb** [BunqCommunity/BunqDesktop#82]
Windows 10 x64 with BunqDesktop 0.7.3

A Payment from the 22th is displayed in the transaction overview in the group for the 23th.

![bunqdesktop-wrong-date](https://user-images.githubusercontent.com/1172106/33175229-533364c8-d05b-11e7-9cd7-f96987b288c7.png)

**Comment by DennisSnijder** [comment]
@janxb Thanks for reporting the issue!
This is a know issue and we are working on it!

Oh and besides this issue, thanks for all your constructive issues! 🎉

**Comment by DennisSnijder** [comment]
@janxb in the next release this issue wil be fixed.
