### ISSUE TITLE
Update strategy

### ISSUE THREAD

**Issue by DennisSnijder** [BunqCommunity/BunqDesktop#9]
Since we are releasing a desktop client we need to be able to easily update the desktop client.

**Comment by DennisSnijder** [comment]
@Crecket any suggestions on how we should approach this?

**Comment by Knight1** [comment]
You could use the protected branches feature and only push to master / prod for releases. If the master commit is not the same as the one in the build you could prompt with a message and or download the new version from the releases.

**Comment by DennisSnijder** [comment]
@Knight1 this is indeed a solution, but i'd rather depend on releases than a certain branch.

**Comment by Crecket** [comment]
The easiest solution would be checking the [Github release api](https://api.github.com/repos/BunqCommunity/BunqDesktop/releases)
