### ISSUE TITLE
Refunded MasterCard payments show Tap&Pay as payment type

### ISSUE THREAD

**Issue by janxb** [BunqCommunity/BunqDesktop#94]
BunqDesktop 0.7.4 on Windows 10 x64

A refunded MasterCard payment is shown with payment type "Tap & Pay". This is not correct, it was an online eCommerce transaction with my normal mastercard.

Second small opinion: I think the text line below the amount ("The payment [..] has status [..]") can be left out. It makes the interface more cluttered and the included information is also visible below in the table.

![bunq-mastercard-refund](https://user-images.githubusercontent.com/1172106/33709921-394edd00-db3f-11e7-95a1-38bcc066920a.png)

**Comment by Crecket** [comment]
Thanks! We're still working on properly implementing the different authorization statuses/types so let me know if you find any other incorrect values :)

**Comment by basst85** [comment]
You can also use "applied_limit" to determine the "Payment Type":
CARD_LIMIT_POS_ICC (normal card payment)
CARD_LIMIT_CONTACTLESS (card payment, contactless)
CARD_LIMIT_WALLET (mobile NFC payment).

And you can use the value of label_card.type:
MASTERCARD
MAESTRO 
MAESTRO_MOBILE_NFC
