### ISSUE TITLE
Failed to create a new session error message - API key loading issue

### ISSUE THREAD

**Issue by SpaceK33z** [BunqCommunity/BunqDesktop#96]
Versions: macOS 10.13.1 and BunqDesktop 0.7.4

1. I enter a password and fill in the API key.
1. The app successfully loads and everything works.
1. I quit the application and start it again.
1. I fill in the password I previously entered, and then get this message:

![screen shot 2017-12-10 at 13 09 40](https://user-images.githubusercontent.com/533616/33804721-681ba870-ddab-11e7-847c-01a7110d309d.png)

Even if I use the "Use no password" button I get the same error.

Let me know if you need any more information, I'm a developer myself :).

**Comment by Crecket** [comment]
Are you using an API key with a fixed IP or a wildcard IP address?

**Comment by SpaceK33z** [comment]
Wildcard. Do note that it does work if I fill in my API key again, it's just that after every restart I need to fill it in again.

**Comment by Crecket** [comment]
@SpaceK33z do you have telegram or something else I can contact you on? I have a dev version with a new logger which I don't want to release publicly just yet. It will hopefully help with debugging the issue

**Comment by IngeN86** [comment]
So now i have to put it here? I downloaded older ones but still same problem... I can not do anything.

**Comment by basst85** [comment]
I think the error of @IngeN86 had to do with the "Wildcard IP" API setting. Maybe this setting was not active and you received a new IP-address from your provider..

**Comment by IngeN86** [comment]
So i have to get a new api key? I dont even know the difference between wildcard api and normal sorry;) I just got it from the app like it was said to do... so dont know what i can do different  so it does not happen again?

**Comment by Crecket** [comment]
@IngeN86 When you generate the key, you can select it and then hit the "Allow All IP-Addresses" button. 

![image](https://user-images.githubusercontent.com/7481136/35768022-422ecbda-08f6-11e8-9616-788ebd816f6c.png)

It will say something similar in Dutch if you're not using English obviously

**Comment by IngeN86** [comment]
But can i generate a key the again on the same phone? Since it says its not possible? Cause i used a phone of a neighbour to get it..and then i would have to use that one again.

**Comment by Crecket** [comment]
Some of the improvements which have been implemented now.
 - Duplicate sessions for a single installation should no longer be created (which is the cause of this issue)
 - If invalid data is stored it should reset the existing invalid session/installation and create a new one
 - More log messages to make debugging easier in the future

Since reproducing this issue is difficult I'm not entirely sure if all scenarios are fixed but we'll create a new issue if that is the case
