### ISSUE TITLE
Copy/paste shortcuts are disabled

### ISSUE THREAD

**Issue by SpaceK33z** [BunqCommunity/BunqDesktop#97]
Versions: macOS 10.13.1 and BunqDesktop 0.7.4

The only way to paste the API key (or any other field) seems to be to right click on the input and click on "Paste". The native macOS shortcuts, `cmd+c` and `cmd+v` (also `cmd+a` to select all text) seem to be disabled. Is there a specific reason for this?

**Comment by DennisSnijder** [comment]
@SpaceK33z The issue has been fixed. Once we do a new release you can download the new version including the fix 😄
