### ISSUE TITLE
We received the following error while loading your master card payments: The item you requested could not be found.

### ISSUE THREAD

**Issue by remcomldr** [BunqCommunity/BunqDesktop#98]
I get this error, since i paid for a diffenent credit card (not a bunq card)

**Comment by Crecket** [comment]
What do you mean with paying for a different card? And does that error occur when you try to view information on the payment or does it happen on the main page?

**Comment by remcomldr** [comment]
I get the error in the account overview, it's an ideal payment to ICS, since this payment i get this error and only on the account the payment has been made from.
